/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Sub_Zero
 */
public class Exemplos extends javax.swing.JFrame {

    /**
     * Creates new form Exemplos
     */
    public Exemplos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jVariaveis = new javax.swing.JLabel();
        Expressoes = new javax.swing.JLabel();
        jEstruturaDecisao = new javax.swing.JLabel();
        jButtonAritmeticas = new javax.swing.JButton();
        jButtonLogicas = new javax.swing.JButton();
        jButtonRelacionais = new javax.swing.JButton();
        jButtonSeSenao = new javax.swing.JButton();
        jButtonEscolha = new javax.swing.JButton();
        jEstruturaRepeticao = new javax.swing.JLabel();
        jButtonPara = new javax.swing.JButton();
        jButtonEnquanto = new javax.swing.JButton();
        jButtonRepita = new javax.swing.JButton();
        jEstruturaDados = new javax.swing.JLabel();
        jButtonRegistro = new javax.swing.JButton();
        jButtonVetor = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jModulo = new javax.swing.JLabel();
        jButtonModulo = new javax.swing.JButton();
        jButtonVariaveis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exemplos");
        setResizable(false);

        jVariaveis.setText("Declaração:");

        Expressoes.setText("Expressão:");

        jEstruturaDecisao.setText("Estrutura de Decisão:");

        jButtonAritmeticas.setText("Aritmética");
        jButtonAritmeticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAritmeticasActionPerformed(evt);
            }
        });

        jButtonLogicas.setText("Lógica");
        jButtonLogicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogicasActionPerformed(evt);
            }
        });

        jButtonRelacionais.setText("Relacional");
        jButtonRelacionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelacionaisActionPerformed(evt);
            }
        });

        jButtonSeSenao.setText("Se .. Senao");
        jButtonSeSenao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeSenaoActionPerformed(evt);
            }
        });

        jButtonEscolha.setText("Escolha");
        jButtonEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscolhaActionPerformed(evt);
            }
        });

        jEstruturaRepeticao.setText("Estrutura de Repetição:");

        jButtonPara.setText("Para");
        jButtonPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParaActionPerformed(evt);
            }
        });

        jButtonEnquanto.setText("Enquanto");
        jButtonEnquanto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnquantoActionPerformed(evt);
            }
        });

        jButtonRepita.setText("Repita .. ate");
        jButtonRepita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepitaActionPerformed(evt);
            }
        });

        jEstruturaDados.setText("Estrutura de Dados:");

        jButtonRegistro.setText("Registro");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        jButtonVetor.setText("Vetor e Matriz");
        jButtonVetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVetorActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jModulo.setText("Módulo:");

        jButtonModulo.setText("Módulo");
        jButtonModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuloActionPerformed(evt);
            }
        });

        jButtonVariaveis.setText("Variáveis");
        jButtonVariaveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVariaveisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jVariaveis)
                            .addComponent(Expressoes)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonSeSenao, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(jButtonEscolha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonAritmeticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonRelacionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonLogicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonVariaveis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                                .addComponent(jEstruturaDecisao, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEstruturaRepeticao)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonVetor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRepita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEnquanto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonPara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEstruturaDados)
                            .addComponent(jModulo))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jModulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEstruturaDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEstruturaRepeticao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnquanto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRepita))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jVariaveis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonVariaveis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jEstruturaDecisao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonSeSenao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonEscolha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Expressoes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonAritmeticas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonRelacionais)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonLogicas))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButtonAritmeticasActionPerformed(java.awt.event.ActionEvent evt) {  
    	String ex1 = "inicio"+
					"\n     real: a , b , c , res;"+
					"\n     escreva( \"Entre com o valor da variavel a: \" );"+
					"\n     leia( a );"+
					"\n     escreva( \"Entre com o valor da variavel b: \" );"+
					"\n     leia( b );"+
					"\n     escreva( \"Entre com o valor da variavel c: \" );"+
					"\n     leia( c );"+
					"\n     res <- ( 3.0 * a + 2.0 * b ) / ( c - ( a - 1.0 ) / ( 1.0 + ( a + b ) / ( 2.0 * c ) ) );"+
					"\n     escreva ( \"O resultado da expressao e: \", res );"+
					"\nfimalgoritmo";
    	String ex2 = "inicio"+
					 "\n     inteiro:n,resMod;"+
    				 "\n     escreva(\"Numero: \");"+
    				 "\n     leia (n);"+
    				 "\n     resMod <- mod(numero,2);"+
    				 "\n     se( resMod = 0) entao"+
    				 "\n           escreva (\"O valor e par!\");"+
    				 "\n     fimse;"+
    				 "\n     se (resMod = 1) entao"+
    				 "\n           escreva (\"O valor e impar!\");"+
    				 "\n     fimse;"+
    				 "\nfimalgoritmo";
    	String ex3 = "inicio"+
				 "\n     inteiro:n,resDiv;"+
				 "\n     escreva(\"Numero: \");"+
				 "\n     leia (n);"+
				 "\n     resDiv <- div(numero,2);"+
				 "\n     escreva(resDiv);"+
				 "\nfimalgoritmo";
        CodigoExemplo codigoEx = new CodigoExemplo("Exemplos de Expressão Aritmética","Exemplo 1:\n"+ex1+"\n\n\nExemplo 2:\n"+ex2+"\n\n\nExemplo 3:\n"+ex3);
        codigoEx.show();
    }                                                  

    private void jButtonRelacionaisActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String ex1 = "inicio"+
					"\n     inteiro:idade<-18;"+
        			"\n     se(idade>=18)entao"+
        			"\n          escreva(\"Maior de idade\");"+
        			"\n     fimse;"+
        			"\nfimalgoritmo";
        String ex2 = "inicio"+
        			"\n     real:salario<-25000;"+
        			"\n     se(salario<2000)entao"+
        			"\n          escreva(\"Continue estudando! :(\");"+
        			"\n     fimse;"+
        			"\n     se(salario>25000)entao"+
					"\n          escreva(\"Continue estudando!, :) kkkkkk\");"+
					"\n     fimse;"+
					"\nfimalgoritmo";
    	CodigoExemplo codigoEx = new CodigoExemplo("Exemplos de Expressão Relacional","Exemplo 1:\n"+ex1+"\n\n\nExemplo 2:\n"+ex2);
        codigoEx.show();
    }                                                  

    private void jButtonLogicasActionPerformed(java.awt.event.ActionEvent evt) { 
    	String ex1 = "inicio"+
	    			"\n     inteiro:idade<-12;"+
	    			"\n     se(idade>=12 e idade <= 17) entao"+
	    			"\n          escreva(\"Voce e um adolescente!\");"+
	    			"\n     fimse;"+
	    			"\n     se(idade>=18 e idade <= 35) entao"+
	    			"\n          escreva(\"Voce e Jovem!\");"+
	    			"\n     fimse;"+
	    			"\n     se(idade<>18) entao"+
	    			"\n          escreva(\"Voce nao tem 18 anos!\");"+
	    			"\n     fimse;"+
	    			"\n     se(idade<12 ou idade>65)entao"+
	    			"\n          escreva(\"ok\");"+
	    			"\n     fimse;"+
	    			"\nfimalgoritmo";
        CodigoExemplo codigoEx = new CodigoExemplo("Exemplo de Expressão Lógica","Exemplo 1:\n"+ex1);
        codigoEx.show();
    }                                              

    private void jButtonSeSenaoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String ex1 = "var:"+
					"\n      inteiro: idade;"+
					"\ninicio"+
					"\n      escreva(\"Informe a idade do nadador: \");"+
					"\n      leia(idade);"+
					"\n      se(idade < 5) entao"+
					"\n            inicio"+
					"\n            escreva(\"O atleta nao pode participar, idade abaixo da minima permitida.\");"+
					"\n            fim;"+
					"\n      fimse;"+
					"\n      se(idade >= 5 e idade <= 7) entao"+
					"\n            escreva(\"O atleta tem \" , idade, \" anos,ele esta na categoria INFANTIL A\");"+
					"\n      fimse;"+
					"\n      se(idade > 7 e idade <= 10) entao"+
					"\n            escreva(\"O atleta tem \" , idade , \" anos, ele esta na categoria INFANTIL B\");"+
					"\n      fimse;"+
					"\n      se(idade > 10 e idade <= 13) entao"+
					"\n            escreva(\"O atleta tem \" , idade , \" anos, ele esta na categoria JUVENIL A\");"+
					"\n      fimse;"+
					"\n      se(idade > 13 e idade <= 17) entao"+
					"\n            escreva(\"O atleta tem \" , idade , \" anos, ele esta na categoria JUVENIL B\");"+
					"\n      fimse;"+
					"\n      se(idade > 17) entao"+
					"\n            escreva(\"O atleta tem \" , idade, \" anos, ele esta na categoria SENIOR\");"+
					"\n      fimse;"+
					"\nfimalgoritmo";
        String ex2 = "var:"+
        			"\n      inteiro: idade;"+
        			"\ninicio"+
        			"\n      escreva(\"Informe a idade do nadador: \");"+
        			"\n      leia(idade);"+
        			"\n      se(idade < 5) entao"+
        			"\n            inicio"+
        			"\n            escreva(\"O atleta nao pode participar, idade abaixo da minima permitida.\");"+
        			"\n            fim;"+
        			"\n      senao"+
        			"\n            inicio"+
        			"\n            se(idade >= 5 e idade <= 7) entao"+
        			"\n                        escreva(\"O atleta tem \" , idade, \" anos,ele esta na categoria INFANTIL A\");"+
        			"\n            senao"+
        			"\n                        se(idade > 7 e idade <= 10) entao"+
        			"\n                                    escreva(\"O atleta tem \" , idade , \" anos, ele esta na categoria INFANTIL B\");"+
        			"\n                        senao"+
        			"\n                                   se(idade > 10 e idade <= 13) entao"+
        			"\n                                               escreva(\"O atleta tem \" , idade , \" anos, ele esta na categoria JUVENIL A\");"+
        			"\n                                    senao"+
        			"\n                                               se(idade > 13 e idade <= 17) entao"+
        			"\n                                                            escreva(\"O atleta tem \" , idade , \" anos, ele esta na categoria JUVENIL B\");"+
        			"\n                                                senao"+
        			"\n                                                           se(idade > 17) entao"+
        			"\n                                                                        escreva(\"O atleta tem \" , idade, \" anos, ele esta na categoria SENIOR\");"+
        			"\n                                                            fimse;"+ 
        			"\n                                                fimse;"+
        			"\n                                    fimse;"+ 
        			"\n                        fimse;"+
        			"\n            fimse;"+
        			"\n            fim;"+
        			"\n      fimse;"+
        			"\nfimalgoritmo";
    	CodigoExemplo codigoEx = new CodigoExemplo("Exemplos da Estrutura de decisão Se .. Senao","Exemplo 1:\n"+ex1+"\n\n\nExemplo 2:\n"+ex2);
        codigoEx.show();
    }                                              

    private void jButtonEscolhaActionPerformed(java.awt.event.ActionEvent evt) {             
    	String ex1 = "inicio"+
					 "\n     inteiro: codigo;"+
					 "\n     escreva (\"O CODIGO E CATEGORIA DE UM NADADOR \");"+
					 "\n     escreva (\"Codigo------Categoria\");"+
					 "\n     escreva (\"  1001-------Infantil\");"+
					 "\n     escreva (\"  1002-------Juvenil\");"+
					 "\n     escreva (\"  1003-------Adolescente\");"+
					 "\n     escreva (\"  1004-------Senior\");"+
					 "\n     escreva (\"  1005-------Profissional\");"+
					 "\n     escreva (\"  1006-------MASTER\");"+
					 "\n     escreva (\"Insira o codigo do nadador\");"+
					 "\n     leia(codigo);"+
					 "\n     escolha codigo"+
					 "\n           caso 1001: escreva (\" Sua categoria e Infantil\");"+
					 "\n           caso 1002: escreva (\" Sua categoria e Juvenil\");"+
					 "\n           caso 1003: escreva (\" Sua categoria e Adolescente\");"+
					 "\n           caso 1004: escreva (\" Sua categoria e Senior\");"+
					 "\n           caso 1005: escreva (\" Sua categoria e Profissional\");"+
					 "\n           caso 1006: escreva (\" Sua categoria e Master\");"+
					 "\n           caso contrario: escreva (\"Codigo fora da faixa!\");"+
					 "\n     fimescolha;"+
					 "\nfimalgoritmo";
        CodigoExemplo codigoEx = new CodigoExemplo("Exemplo da Estrutura de decisão Escolha","Exemplo 1:\n"+ex1);
        codigoEx.show();
    }                                              

    private void jButtonParaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String ex1 = "var:"+
        			 "\n   tipo NOME = vetor [1..10] de caractere; {definição do tipo do vetor}"+
        			 "\n   tipo Pessoa = registro"+
        			 "\n      NOME:nome;"+
        			 "\n      real:nota;"+
        			 "\n      inteiro:serie;"+
        			 "\n   fimregistro;"+
        			 "\ninicio"+
        			 "\n   inteiro:i,J;"+
        			 "\n   tipo PESSOA = vetor [1..2] de Pessoa; {definição do tipo do vetor}"+
        			 "\n   PESSOA:p;"+
        			 "\n   para i de 0 ate 1 faca"+
        			 "\n      escreva(\"informe o nome do \" ,i,\" aluno: \");"+
        			 "\n      leia(p[i].nome);"+
        			 "\n      escreva(\"informe a serie: \");"+
        			 "\n      leia(p[i].serie);"+
        			 "\n      escreva(\"informe a nota do aluno: \");"+
        			 "\n      leia(p[i].nota);"+
        			 "\n      escreva(\"\");"+
        			 "\n   fimpara;"+
        			 "\n   escreva(\"    Relatorio Escolar  \");"+
        			 "\n   para J de 0 ate 1 faca"+
        			 "\n      escreva(\"--------------------\");"+
        			 "\n      escreva(\"NOME:\"  ,p[J].nome);"+
        			 "\n      escreva(\"SERIE:\" ,p[J].serie,\"º\");"+
        			 "\n      escreva(\"NOTA:\" ,p[J].nota);"+
        			 "\n   fimpara;"+
        			 "\nfimalgoritmo";
    	CodigoExemplo codigoEx = new CodigoExemplo("Exemplos da Estrutura de repetição Para","Exemplo 1:\n"+ex1);
        codigoEx.show();
    }                                           

    private void jButtonEnquantoActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	String ex1 = "var:"+
    				 "\n   tipo NOME = vetor [1..10] de caractere; {definição do tipo do vetor}"+
		   			 "\n   tipo Pessoa = registro"+
		   			 "\n      NOME:nome;"+
		   			 "\n      real:nota;"+
		   			 "\n      inteiro:serie;"+
		   			 "\n   fimregistro;"+
		   			 "\ninicio"+
		   			 "\n   inteiro:i<-0,J<-0;"+
        			 "\n   tipo PESSOA = vetor [1..2] de Pessoa; {definição do tipo do vetor}"+
        			 "\n   PESSOA:p;"+
		   			 "\n   enquanto(i<2) faca"+
		   			 "\n      escreva(\"informe o nome do \" ,i,\" aluno: \");"+
		   			 "\n      leia(p[i].nome);"+
		   			 "\n      escreva(\"informe a serie: \");"+
		   			 "\n      leia(p[i].serie);"+
		   			 "\n      escreva(\"informe a nota do aluno: \");"+
		   			 "\n      leia(p[i].nota);"+
		   			 "\n      escreva(\"\");"+
		   			 "\n      i<-i+1;"+
		   			 "\n   fimenquanto;"+
		   			 "\n   escreva(\"    Relatorio Escolar  \");"+
		   			 "\n   enquanto(J<2) faca"+
		   			 "\n      escreva(\"--------------------\");"+
		   			 "\n      escreva(\"NOME:\"  ,p[J].nome);"+
		   			 "\n      escreva(\"SERIE:\" ,p[J].serie,\"º\");"+
		   			 "\n      escreva(\"NOTA:\" ,p[J].nota);"+
		   			 "\n      J<-J+1;"+
		  			 "\n   fimenquanto;"+
		   			 "\nfimalgoritmo";
    	CodigoExemplo codigoEx = new CodigoExemplo("Exemplos da Estrutura de repetição Enquanto","Exemplo 1:\n"+ex1);
        codigoEx.show();
    }                                               

    private void jButtonRepitaActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	String ex1 = "var:"+
				 	 "\n   tipo NOME = vetor [1..10] de caractere; {definição do tipo do vetor}"+
	      			 "\n   tipo Pessoa = registro"+
	      			 "\n      NOME:nome;"+
	      			 "\n      real:nota;"+
	      			 "\n      inteiro:serie;"+
	      			 "\n   fimregistro;"+
	      			 "\n   inicio"+
	      			 "\n   inteiro:i<-0,J<-0;"+
        			 "\n   tipo PESSOA = vetor [1..2] de Pessoa; {definição do tipo do vetor}"+
        			 "\n   PESSOA:p;"+
	      			 "\n   repita"+
	      			 "\n      escreva(\"informe o nome do \" ,i,\" aluno: \");"+
	      			 "\n      leia(p[i].nome);"+
	      			 "\n      escreva(\"informe a serie: \");"+
	      			 "\n      leia(p[i].serie);"+
	      			 "\n      escreva(\"informe a nota do aluno: \");"+
	      			 "\n      leia(p[i].nota);"+
	      			 "\n      escreva(\"\");"+
	      			 "\n      i<-i+1;"+
	      			 "\n   ate(i<2);"+
	      			 "\n   escreva(\"    Relatorio Escolar  \");"+
	      			 "\n   repita"+
	      			 "\n      escreva(\"--------------------\");"+
	      			 "\n      escreva(\"NOME:\"  ,p[J].nome);"+
	      			 "\n      escreva(\"SERIE:\" ,p[J].serie,\"º\");"+
	      			 "\n      escreva(\"NOTA:\" ,p[J].nota);"+
	      			 "\n      J<-J+1;"+
	     			 "\n   ate(J<2);"+
	      			 "\nfimalgoritmo";
    	CodigoExemplo codigoEx = new CodigoExemplo("Exemplos da Estrutura de repetição Repita .. Ate","Exemplo 1:\n"+ex1);
        codigoEx.show();
    }                                             

    private void jButtonVetorActionPerformed(java.awt.event.ActionEvent evt) {
    	String ex1 = "inicio"+
    				"\n    tipo NUM = vetor [1..5] de inteiro; {definição do tipo do vetor}"+
					"\n    NUM:n;"+
    				"\n    inteiro:i,soma;"+
    				"\n    para i de 0 ate 4 faca"+
    				"\n        soma <- soma + n[i];"+
    				"\n    fimpara;"+
    				"\n    escreva(\"Soma: \",soma);"+
    				"\nfimalgoritmo";
    	String ex2 = "inicio"+
    				 "\n    tipo vN = vetor [1..5] de inteiro; {definição do tipo do vetor}"+
    				 "\n    vN:n;"+
    				 "\n    inteiro: k<-3,soma<-0,media;"+
    				 "\n    escreva(\"Numero 1: \");"+
    				 "\n    leia(n[0]);"+
    				 "\n    escreva(\"Numero 2: \");"+
    				 "\n    leia(n[1]);"+
    				 "\n    escreva(\"Numero 3: \");"+
    				 "\n    leia(n[2]);"+
    				 "\n    soma <- soma + n[0];"+
    				 "\n    soma <- soma + n[1];"+
    				 "\n    soma <- soma + n[2];"+
    				 "\n    media <- soma/k;"+
    				 "\n    escreva(\"Media: \",media);"+
    				 "\nfimalgoritmo";
    	String ex3 = "inicio"+
				 "\n    tipo mN = matriz [1..5,1..5] de inteiro; {definição do tipo do vetor}"+
				 "\n    mN:n;"+
				 "\n    inteiro: i,j;"+
				 "\n    para i de 0 ate 4 faca"+
				 "\n        para j de 0 ate 4 faca"+
				 "\n            escreva(\"Numero: \");"+
				 "\n            leia(n[i,j]);"+
				 "\n        fimpara;"+
				 "\n    fimpara;"+
				 "\n    para i de 0 ate 4 faca"+
				 "\n        para j de 0 ate 4 faca"+
				 "\n            escreva(\"Numero: \",n[i,j]);"+
				 "\n        fimpara;"+
				 "\n        escreva(\" \");"+
				 "\n    fimpara;"+
				 "\nfimalgoritmo";
        CodigoExemplo codigoEx = new CodigoExemplo("Exemplo da Estrutura de dados Vetor","Exemplo 1:\n"+ex1+"\n\n\nExemplo 2:\n"+ex2+"\n\n\nExemplo 3:\n"+ex3);
        codigoEx.show();
    }                                            

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String ex1 = "inicio"+
				 	"\n    tipo NOME = vetor [1..10] de caractere; {definição do tipo do vetor}"+
        			"\n    tipo Pessoa = registro"+
					"\n        inteiro: idade;"+
        			"\n        NOME:nome;"+
        			"\n    fimregistro;"+
					"\n    Pessoa:pessoa;"+
					"\n    escreva(\"Nome: \");"+
					"\n    leia(pessoa.nome);"+
					"\n    escreva(\"Idade: \");"+
					"\n    leia(pessoa.idade);"+
					"\n    escreva (\"Nome: \",pessoa.nome);"+
					"\n    escreva (\"Idade: \",pessoa.idade);"+
					"\nfimalgoritmo";
    	CodigoExemplo codigoEx = new CodigoExemplo("Exemplo da Estrutura de dados Registro","Exemplo 1:\n"+ex1);
        codigoEx.show();
    }                                               

    private void jButtonModuloActionPerformed(java.awt.event.ActionEvent evt) {  
    	String ex1 = "var:"+
			 	 	 "\n    tipo NOME = vetor [1..10] de caractere; {definição do tipo do vetor}"+
					 "\n    tipo Pessoa = registro"+
    				 "\n         inteiro: cpf;"+
    				 "\n         real: salario;"+
    				 "\n         NOME:nome;"+
    				 "\n         logico:ativo;"+
    				 "\n    fimregistro;"+
    				 "\n    modulo Calcular (logico: ativo)"+ 
    				 "\n         se(ativo=verdadeiro)entao"+
    			 	 "\n               retorne 2500.0;"+
    				 "\n         senao"+
    				 "\n              retorne 0.0;"+
    				 "\n         fimse;"+
    				 "\n    fimmodulo;"+
    				 "\ninicio"+
    				 "\n    Pessoa:pessoa;"+
    				 "\n    escreva(\"Nome: \");"+
    				 "\n    leia(pessoa.nome);"+
    				 "\n    escreva(\"CPF: \");"+
    				 "\n    leia(pessoa.cpf);"+
    				 "\n    escreva(\"Pessoa ativa: \");"+
    				 "\n    leia(pessoa.ativo);"+
    				 "\n    pessoa.salario <- Calcular(pessoa.ativo);"+
    				 "\n    escreva (\"Salario:  \",pessoa.salario);"+
    				 "\nfimalgoritmo";
    	String ex2 = "var:"+
					 "\n    inteiro:num1,num2,soma;"+
    				 "\n    modulo Calcular ()"+
    				 "\n         retorne num1+num2;"+
    			 	 "\n    fimmodulo;"+
    				 "\ninicio"+
    				 "\n    escreva(\"Numero 1: \");"+
    				 "\n    leia(num1);"+
    				 "\n    escreva(\"Numero 2: \");"+
    				 "\n    leia(num2);"+
    				 "\n    soma <- Calcular();"+
    				 "\n    escreva (\"Soma:  \",soma);"+
    				 "\nfimalgoritmo";
        CodigoExemplo codigoEx = new CodigoExemplo("Exemplos de Módulo","Exemplo 1:\n"+ex1+"\n\n\nExemplo 2:\n"+ex2);
        codigoEx.show();
    }                                             

    private void jButtonVariaveisActionPerformed(java.awt.event.ActionEvent evt) {
    	String ex1 = "var:"+
				 	"\n      tipo NOME = vetor [1..10] de caractere; {definição do tipo do vetor}"+
					"\n      NOME:nome; { para ler o primeiro nome de uma pessoa}"+
					"\n      inteiro:idade;"+
					"\n      real:nota;"+
					"\n      logico:bem;"+
					"\ninicio"+
					"\n      escreva(\"Nome: \");"+
					"\n      leia(nome);"+
					"\n      escreva(\"Idade: \");"+
					"\n      leia(idade);"+
					"\n      escreva(\"Nota: \");"+
					"\n      leia(nota);"+
					"\n      escreva(\"Esta bem: \");"+
					"\n      leia(bem);"+
					"\n      escreva(\"Nome: \",nome,\" Nota: \", nota, \" Idade: \",idade);"+
					"\n      escreva(\"Esta bem: \", bem);"+
					"\nfimalgoritmo";
    	String ex2 = "inicio"+
			 	    "\n      tipo NOME = vetor [1..10] de caractere; {definição do tipo do vetor}"+
					"\n      NOME:nome; { para ler o primeiro nome de uma pessoa}"+
					"\n      inteiro:idade;"+
					"\n      real:nota;"+
					"\n      logico:bem;"+
					"\n      escreva(\"Nome: \");"+
					"\n      leia(nome);"+
					"\n      escreva(\"Idade: \");"+
					"\n      leia(idade);"+
					"\n      escreva(\"Nota: \");"+
					"\n      leia(nota);"+
					"\n      escreva(\"Esta bem: \");"+
					"\n      leia(bem);"+
					"\n      escreva(\"Nome: \",nome,\" Nota: \", nota, \" Idade: \",idade);"+
					"\n      escreva(\"Esta bem: \", bem);"+
					"\nfimalgoritmo";
        CodigoExemplo codigoEx = new CodigoExemplo("Exemplos de declaração de Variável","Exemplo 1:\n"+ex1+"\n\n\nExemplo 2:\n"+ex2);
        codigoEx.show();
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel Expressoes;
    private javax.swing.JButton jButtonAritmeticas;
    private javax.swing.JButton jButtonEnquanto;
    private javax.swing.JButton jButtonEscolha;
    private javax.swing.JButton jButtonLogicas;
    private javax.swing.JButton jButtonModulo;
    private javax.swing.JButton jButtonPara;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JButton jButtonRelacionais;
    private javax.swing.JButton jButtonRepita;
    private javax.swing.JButton jButtonSeSenao;
    private javax.swing.JButton jButtonVariaveis;
    private javax.swing.JButton jButtonVetor;
    private javax.swing.JLabel jEstruturaDados;
    private javax.swing.JLabel jEstruturaDecisao;
    private javax.swing.JLabel jEstruturaRepeticao;
    private javax.swing.JLabel jModulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jVariaveis;
    // End of variables declaration                   
}
