/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Sub_Zero
 */
public class Sobre extends javax.swing.JFrame {

    /**
     * Creates new form Sobre
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPJIniciacao = new javax.swing.JLabel();
        jJosias = new javax.swing.JLabel();
        jVeronica = new javax.swing.JLabel();
        jSancha = new javax.swing.JLabel();
        jProjetoNome = new javax.swing.JLabel();
        jOrientadora = new javax.swing.JLabel();
        jPJPesquisa = new javax.swing.JLabel();
        jLabelLogoUninorte = new javax.swing.JLabel();
        jLabelLogoCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre");
        setResizable(false);

        jPJIniciacao.setText("Desenvolvido pelos graduandos de Ciência da Computação:");

        jJosias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jJosias.setText("Josias Gomes Lima");

        jVeronica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jVeronica.setText("Verônica Luiz de Sousa Pessoa");

        jSancha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSancha.setText("Profª. MSc. Francisca Sancha Azevedo da Silva");

        jProjetoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jProjetoNome.setText("Tradutor de comandos básicos de portugol para a linguagem C");

        jOrientadora.setText("Orientadora:");

        jPJPesquisa.setText("Projeto de Pesquisa:");

        jLabelLogoUninorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/lp_logo_uninorte-manaus.png"))); // NOI18N
        jLabelLogoUninorte.setToolTipText("");

        jLabelLogoCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Sem título.png"))); // NOI18N
        jLabelLogoCurso.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPJIniciacao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jJosias)
                            .addComponent(jVeronica)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jSancha))
                            .addComponent(jOrientadora)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jProjetoNome))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPJPesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelLogoUninorte)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelLogoCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogoUninorte, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPJPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProjetoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jOrientadora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSancha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPJIniciacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jJosias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jVeronica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jJosias;
    private javax.swing.JLabel jLabelLogoCurso;
    private javax.swing.JLabel jLabelLogoUninorte;
    private javax.swing.JLabel jOrientadora;
    private javax.swing.JLabel jPJIniciacao;
    private javax.swing.JLabel jPJPesquisa;
    private javax.swing.JLabel jProjetoNome;
    private javax.swing.JLabel jSancha;
    private javax.swing.JLabel jVeronica;
    // End of variables declaration                   
}
