package Telas;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Reader;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import javax.swing.event.CaretEvent;
//import javax.swing.event.CaretListener;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Sub_Zero
 */
public class TelaPrincipal extends javax.swing.JFrame {

	Arquivo arq2 = new Arquivo();
	
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        try {
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\codigoFonte.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\codigoObjeto.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoTokens.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoTabela.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoErros.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\erroSemantico.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\traducao.txt");
		} catch (IOException e) {
			e.printStackTrace();
		}
        atualizaBarraStatusPortugol();
        atualizaBarraStatusLing_C();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        fileChooserAbrir = new javax.swing.JFileChooser();
        fileChooserSalvarPortugol = new javax.swing.JFileChooser();
        fileChooserSalvar_C = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jExecutar = new javax.swing.JButton();
        jLimparPortugol = new javax.swing.JButton();
        jLimparC = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextC = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPortugol = new javax.swing.JTextArea();
        jStatusPortugol = new javax.swing.JLabel();
        jStatusLing_C = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jArquivo = new javax.swing.JMenu();
        jAbrir = new javax.swing.JMenuItem();
        jSalvarPortugol = new javax.swing.JMenuItem();
        jSalvarLing_C = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenuItem();
        jAjuda = new javax.swing.JMenu();
        jExemplos = new javax.swing.JMenuItem();
        jSobre = new javax.swing.JMenuItem();

        fileChooserAbrir.setApproveButtonToolTipText("");
        fileChooserAbrir.setDialogTitle("Selecione um arquivo .port");
        fileChooserAbrir.setFileFilter( new MyCustomFilter());
        fileChooserAbrir.setFocusCycleRoot(true);

        fileChooserSalvarPortugol.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fileChooserSalvarPortugol.setApproveButtonToolTipText("");
        fileChooserSalvarPortugol.setDialogTitle("Salve um arquivo .port");
        fileChooserSalvarPortugol.setFileFilter( new MyCustomFilter());
        fileChooserSalvarPortugol.setFocusCycleRoot(true);

        fileChooserSalvar_C.setApproveButtonToolTipText("");
        fileChooserSalvar_C.setDialogTitle("Salve um arquivo .c");
        fileChooserSalvar_C.setFileFilter(new MyCustomFilter_C());
        fileChooserSalvar_C.setFocusCycleRoot(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tradutor de Portugol para a Linguagem C");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Linguagem C");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("Portugol");

        jExecutar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jExecutar.setText("Executar");
        jExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExecutarActionPerformed(evt);
            }
        });

        jLimparPortugol.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLimparPortugol.setText("Limpar");
        jLimparPortugol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimparPortugolActionPerformed(evt);
            }
        });

        jLimparC.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLimparC.setText("Limpar");
        jLimparC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimparCActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextC.setColumns(20);
        jTextC.setRows(5);
        jTextC.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextCCaretUpdate(evt);
            }
        });
        jScrollPane6.setViewportView(jTextC);

        jTextPortugol.setColumns(20);
        jTextPortugol.setRows(5);
        jTextPortugol.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextPortugol.setInheritsPopupMenu(true);
        jTextPortugol.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextPortugolCaretUpdate(evt);
            }
        });
        jScrollPane7.setViewportView(jTextPortugol);

        jStatusPortugol.setText("Linha:   Coluna: ");

        jStatusLing_C.setText("Linha:   Coluna: ");

        jArquivo.setText("Arquivo");

        jAbrir.setText("Abrir");
        jAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirActionPerformed(evt);
            }
        });
        jArquivo.add(jAbrir);

        jSalvarPortugol.setText("Salvar (Portugol)");
        jSalvarPortugol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarPortugolActionPerformed(evt);
            }
        });
        jArquivo.add(jSalvarPortugol);

        jSalvarLing_C.setText("Salvar (Ling. C)");
        jSalvarLing_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarLing_CActionPerformed(evt);
            }
        });
        jArquivo.add(jSalvarLing_C);

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jArquivo.add(jSair);

        jMenuBar1.add(jArquivo);

        jAjuda.setText("Ajuda");

        jExemplos.setText("Exemplos");
        jExemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExemplosActionPerformed(evt);
            }
        });
        jAjuda.add(jExemplos);

        jSobre.setText("Sobre");
        jSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSobreActionPerformed(evt);
            }
        });
        jAjuda.add(jSobre);

        jMenuBar1.add(jAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jStatusPortugol)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(109, 109, 109)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(91, 91, 91))))
                                    .addComponent(jStatusLing_C, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLimparPortugol)
                        .addGap(160, 160, 160)
                        .addComponent(jExecutar)
                        .addGap(145, 145, 145)
                        .addComponent(jLimparC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStatusPortugol)
                    .addComponent(jStatusLing_C))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLimparC)
                    .addComponent(jExecutar)
                    .addComponent(jLimparPortugol))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jLimparCActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	jTextC.setText("");
    	try {
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\codigoFonte.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\codigoObjeto.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoTokens.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoTabela.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoErros.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\erroSemantico.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\traducao.txt");
		} catch (IOException e) {
			e.printStackTrace();
		}
        atualizaBarraStatusLing_C();
    }                                        

    private void jLimparPortugolActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	jTextPortugol.setText("");
    	try {
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\codigoFonte.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\codigoObjeto.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoTokens.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoTabela.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoErros.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\erroSemantico.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\traducao.txt");
		} catch (IOException e) {
			e.printStackTrace();
		}
    	atualizaBarraStatusPortugol();
    }                                               

    private void jExecutarActionPerformed(java.awt.event.ActionEvent evt) {  
    	Erro erro = new Erro();
    	int erroLexico = 0;
    	int erroSintatico = 0;
    	int erroSemantico = 0;
    	
    	//criar ou deletar o arquivo caso ele já existir -- evitando lixo de memória!
    	try {
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\codigoFonte.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\codigoObjeto.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoTokens.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoTabela.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\ArquivoErros.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\erroSemantico.txt");
			CriarOuDeletarArquivo("C:\\Windows\\Temp\\traducao.txt");
		} catch (IOException e) {
			e.printStackTrace();
		}
    	
    	//Gravando em arquivo o conteúdo do TextArea do Portugol
    	try {
    		File arquivo = new File("C:\\Windows\\Temp\\codigoFonte.txt");
    		
    		FileWriter fw = new FileWriter(arquivo, true);
    		 
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(jTextPortugol.getText());
            bw.newLine();
            
            bw.close();
            fw.close();
            
            //Chamar o metódo que faz a Análise Léxica
            arq2.AnaliseLexica();
            
    	} catch (IOException e) { 
    		e.printStackTrace();
    	}
    	
    	//Gravar a tabela hash em Arquivo
    	Tabela.mostrarhash();
    	
    	try {
			//Gravando em arquivo o conteúdo do TextArea do Portugol
    		File arquivoerro = new File("C:\\Windows\\Temp\\ArquivoErros.txt");
    		
    		Reader fwo = new FileReader(arquivoerro);
   		 
			BufferedReader bwo = new BufferedReader(fwo);
			String linha;
			linha = bwo.readLine();
			
			if(linha!=null){
				//erro.jErro.setText("Token(s) Inválido(s): \n\n");
				erroLexico = 1;
			}
				
			
			while (linha != null){
				erro.jErro.setText(erro.jErro.getText() +"    "+ linha + "\n");
				linha = bwo.readLine();
			}
			
			bwo.close();
			fwo.close();
    	} catch (IOException e) { 
    		e.printStackTrace();
    	}
    	
    	//chamando o analisador sintatico
        try {
			EG3 eg = new EG3("C:\\Windows\\Temp\\codigoFonte.txt");
			if(eg.simerro==1){
	        	//erro.jErro.setText(erro.jErro.getText()+"\n\nErro Sintático: \n\n");
	        	erro.jErro.setText(erro.jErro.getText()+"     - "+eg.erro);
	        	erroSintatico = 1;
	        }
			/*if(eg.simerro==1){
	        	erro.jErro.setText(erro.jErro.getText()+"\n\nErro Sintático: \n\n");
	        	erro.jErro.setText(erro.jErro.getText()+"    "+eg.erro);
	        	erro.show();
	        }else{
	        	if(erroLexico==1)
	        		erro.show();
	        }*/
		} catch (IOException e) {
			e.printStackTrace();
		}
        //impressão dos erros semânticos
        try {
			//Gravando em arquivo o conteúdo do TextArea do Portugol
    		File arquivoerro = new File("C:\\Windows\\Temp\\erroSemantico.txt");
    		
    		Reader fwo = new FileReader(arquivoerro);
   		 
			BufferedReader bwo = new BufferedReader(fwo);
			String linha;
			linha = bwo.readLine();
			
			if(linha!=null){
				//erro.jErro.setText(erro.jErro.getText() +"\n\nErro(s) Semântico(s): \n\n");
				erroSemantico = 1;
			}
				
			
			while (linha != null){
				erro.jErro.setText(erro.jErro.getText() +"     - "+ linha + "\n");
				linha = bwo.readLine();
			}
			
			bwo.close();
			fwo.close();
    	} catch (IOException e) { 
    		e.printStackTrace();
    	}
        
        if(erroLexico==1 || erroSintatico==1 || erroSemantico==1){
        	erro.jErro.setCaretPosition(0);
        	erro.show();
        }else{
        	try {
    			//Gravando em arquivo o conteúdo do TextArea do Portugol
        		File arquivoTraduzido = new File("C:\\Windows\\Temp\\traducao.txt");
        		
        		Reader fwo = new FileReader(arquivoTraduzido);
       		 
    			BufferedReader bwo = new BufferedReader(fwo);
    			String linha;
    			linha = bwo.readLine();
    			jTextC.setText("");
    			while (linha != null){
    				jTextC.setText(jTextC.getText()+linha+"\n");
    				linha = bwo.readLine();
    			}
    			
    			bwo.close();
    			fwo.close();
    			jTextC.setCaretPosition(0);
        	} catch (IOException e) { 
        		e.printStackTrace();
        	}        	
        	JOptionPane.showMessageDialog (null, "Traduzido com sucesso!\n", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
        Tabela.excluirtabelahash();
    }                                         

    private void jAbrirActionPerformed(java.awt.event.ActionEvent evt) {                                       
        int returnVal = fileChooserAbrir.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooserAbrir.getSelectedFile();
            try {
              // What to do with the file, e.g. display it in a TextArea
              jTextPortugol.read( new FileReader( file.getAbsolutePath() ), null );
              jTextPortugol.setCaretPosition(0);
            } catch (IOException ex) {
              ex.printStackTrace();
            }
        }
    }                                      

    private void jSalvarPortugolActionPerformed(java.awt.event.ActionEvent evt) {                                                
        int returnVal = fileChooserSalvarPortugol.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try{
                File arq = fileChooserSalvarPortugol.getSelectedFile();
                String pathArquivo = arq.getPath().replace(".port", "")+".port";
                
                CriarOuDeletarArquivo(pathArquivo);
                
                File arquivo = new File(pathArquivo);
                FileWriter fw = new FileWriter(arquivo, true);

                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(jTextPortugol.getText());
                bw.newLine();

                bw.close();
                fw.close();
            }catch(IOException ex){
                ex.printStackTrace();
            }
        }
    }                                               

    private void jSalvarLing_CActionPerformed(java.awt.event.ActionEvent evt) {                                              
        int returnVal = fileChooserSalvar_C.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try{
                File arq = fileChooserSalvar_C.getSelectedFile();
                String pathArquivo = arq.getPath().replace(".c", "")+".c";
                
                CriarOuDeletarArquivo(pathArquivo);
                
                File arquivo = new File(pathArquivo);
                FileWriter fw = new FileWriter(arquivo, true);

                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(jTextC.getText());
                bw.newLine();

                bw.close();
                fw.close();
            }catch(IOException ex){
                ex.printStackTrace();
            }
        }
    }                                             

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {                                      
        System.exit(0);
    }                                     

    private void jSobreActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Sobre sobre = new Sobre();
        sobre.show();
    }                                      

    private void jExemplosActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Exemplos exemplos = new Exemplos();
        exemplos.show();
    }                                         

    private void jTextPortugolCaretUpdate(javax.swing.event.CaretEvent evt) {                                          
        /*jTextPortugol.addCaretListener(new CaretListener() {
			public void caretUpdate(CaretEvent e) {
				atualizaBarraStatusPortugol();
			}
        });*/
        atualizaBarraStatusPortugol();
    }                                         

    private void jTextCCaretUpdate(javax.swing.event.CaretEvent evt) {                                   
        atualizaBarraStatusLing_C();
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JFileChooser fileChooserAbrir;
    private javax.swing.JFileChooser fileChooserSalvarPortugol;
    private javax.swing.JFileChooser fileChooserSalvar_C;
    private javax.swing.JMenuItem jAbrir;
    private javax.swing.JMenu jAjuda;
    private javax.swing.JMenu jArquivo;
    private javax.swing.JButton jExecutar;
    private javax.swing.JMenuItem jExemplos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jLimparC;
    private javax.swing.JButton jLimparPortugol;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jSair;
    private javax.swing.JMenuItem jSalvarLing_C;
    private javax.swing.JMenuItem jSalvarPortugol;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuItem jSobre;
    private javax.swing.JLabel jStatusLing_C;
    private javax.swing.JLabel jStatusPortugol;
    private javax.swing.JTextArea jTextC;
    private javax.swing.JTextArea jTextPortugol;
    // End of variables declaration                   

    private void CriarOuDeletarArquivo (String arq) throws IOException{
    	File arquivo = new File(arq);
    	if (!arquivo.exists()) {
	        //cria um arquivo (vazio)
	        arquivo.createNewFile();
	    }else{
	        arquivo.delete();
	        arquivo.createNewFile();
	    }
    }
    
    private static class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".port");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Algoritmos portugol (*.port)";
        }
    }

    private static class MyCustomFilter_C extends FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".c");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Linguagem C (*.c)";
        }
    }
    
    private void atualizaBarraStatusPortugol() {
    int pos = jTextPortugol.getCaretPosition();
    int linha = 0;
    int coluna = 0;
    try {
      linha = jTextPortugol.getLineOfOffset(pos);
      coluna = pos - jTextPortugol.getLineStartOffset(linha);
    }
    catch (Exception e) {}

   	jStatusPortugol.setText("Linha: " + (linha+1) + "  Coluna: " + (coluna+1));
  }
    
  private void atualizaBarraStatusLing_C() {
    int pos = jTextC.getCaretPosition();
    int linha = 0;
    int coluna = 0;
    try {
      linha = jTextC.getLineOfOffset(pos);
      coluna = pos - jTextC.getLineStartOffset(linha);
    }
    catch (Exception e) {}

   	jStatusLing_C.setText("Linha: " + (linha+1) + "  Coluna: " + (coluna+1));
  }
}
