/* Generated by JTB 1.4.7 */
package Telas.visitor;

import Telas.syntaxtree.*;
import java.util.*;

public class DepthFirstRetVisitor<R> implements IRetVisitor<R> {


  public R visit(final NodeChoice n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    final R nRes = n.choice.accept(this);
    return nRes;
  }

  public R visit(final NodeList n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    R nRes = null;
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      @SuppressWarnings("unused")
      final R sRes = e.next().accept(this);
    }
    return nRes;
  }

  public R visit(final NodeListOptional n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    if (n.present()) {
      R nRes = null;
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        @SuppressWarnings("unused")
        R sRes = e.next().accept(this);
        }
      return nRes;
    } else
      return null;
  }

  public R visit(final NodeOptional n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    if (n.present()) {
      final R nRes = n.node.accept(this);
      return nRes;
    } else
      return null;
  }

  public R visit(final NodeSequence n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    R nRes = null;
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      @SuppressWarnings("unused")
      R subRet = e.next().accept(this);
    }
    return nRes;
  }

  public R visit(final NodeTCF n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    R nRes = null;
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return nRes;
  }

  public R visit(final NodeToken n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    R nRes = null;
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return nRes;
  }

  public R visit(final Start n) {
    R nRes = null;
    // f0 -> Programa()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Programa n) {
    R nRes = null;
    // f0 -> ( #0 <VAR>
    // .. .. . #1 ( %0 GDecl()
    // .. .. . .. | %1 FunDeclaracao() )+ )?
    n.f0.accept(this);
    // f1 -> <INICIO_LITERAL>
    n.f1.accept(this);
    // f2 -> Declaracao()
    n.f2.accept(this);
    // f3 -> <FIMALGORITMO>
    n.f3.accept(this);
    // f4 -> <EOF>
    n.f4.accept(this);
    return nRes;
  }

  public R visit(final Declaracao n) {
    R nRes = null;
    // f0 -> GlobalDeclaracao()
    n.f0.accept(this);
    // f1 -> ( CorpoDeclLista() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final GlobalDeclaracao n) {
    R nRes = null;
    // f0 -> ( GDecl() )*
    n.f0.accept(this);
    // f1 -> ( CorpoDeclLista() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final GDecl n) {
    R nRes = null;
    // f0 -> . %0 #0 <Tipo> #1 <IDENTIFIER> #2 <IGUAL> #3 DefTipo()
    // .. .. | %1 VarDeclaracao()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final DefTipo n) {
    R nRes = null;
    // f0 -> . %0 #0 <Registro>
    // .. .. . .. #1 ( VarDeclaracao() )+
    // .. .. . .. #2 <FimRegistro> #3 <PONTOEVIRGULA>
    // .. .. | %1 #0 <VETOR> #1 <ACOLCHETE> #2 <DIGITO> #3 <PONTOS> #4 <DIGITO> #5 <FCOLCHETE> #6 <DE>
    // .. .. . .. #7 ( &0 <TIPO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #8 <PONTOEVIRGULA>
    // .. .. | %2 #0 <MATRIZ> #1 <ACOLCHETE> #2 <DIGITO> #3 <PONTOS> #4 <DIGITO>
    // .. .. . .. #5 ( $0 <VIRGULA> $1 <DIGITO> $2 <PONTOS> $3 <DIGITO> )+
    // .. .. . .. #6 <FCOLCHETE> #7 <DE>
    // .. .. . .. #8 ( &0 <TIPO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #9 <PONTOEVIRGULA>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final TipoEspecificador n) {
    R nRes = null;
    // f0 -> . %0 <TIPO>
    // .. .. | %1 <IDENTIFIER>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final VarDeclaracao n) {
    R nRes = null;
    // f0 -> TipoEspecificador()
    n.f0.accept(this);
    // f1 -> <DOISPONTOS>
    n.f1.accept(this);
    // f2 -> VarDeclaracaoI()
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final VarDeclaracaoI n) {
    R nRes = null;
    // f0 -> VarListaNum()
    n.f0.accept(this);
    // f1 -> <PONTOEVIRGULA>
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final VarListaNum n) {
    R nRes = null;
    // f0 -> VarItemNum()
    n.f0.accept(this);
    // f1 -> ( VNum() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final VNum n) {
    R nRes = null;
    // f0 -> <VIRGULA>
    n.f0.accept(this);
    // f1 -> VarItemNum()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final VarItemNum n) {
    R nRes = null;
    // f0 -> <IDENTIFIER>
    n.f0.accept(this);
    // f1 -> VarItemVetor()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final VarItemVetor n) {
    R nRes = null;
    // f0 -> ( #0 <RECEBE> #1 VarComplemento() )?
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final VarComplemento n) {
    R nRes = null;
    // f0 -> . %0 #0 ( <MENOS> )?
    // .. .. . .. #1 <DIGITO>
    // .. .. | %1 #0 ( <MENOS> )?
    // .. .. . .. #1 <IDENTIFIER>
    // .. .. | %2 #0 ( <MENOS> )?
    // .. .. . .. #1 <PONTO_FLUTUANTE>
    // .. .. | %3 <STRING>
    // .. .. | %4 <FALSO>
    // .. .. | %5 <VERDADEIRO>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final FunDeclaracao n) {
    R nRes = null;
    // f0 -> <MODULO>
    n.f0.accept(this);
    // f1 -> <IDENTIFIER>
    n.f1.accept(this);
    // f2 -> <APARENTESE>
    n.f2.accept(this);
    // f3 -> ( Params() )?
    n.f3.accept(this);
    // f4 -> <FPARENTESE>
    n.f4.accept(this);
    // f5 -> CompostoDecl()
    n.f5.accept(this);
    // f6 -> <FIMMODULO>
    n.f6.accept(this);
    // f7 -> <PONTOEVIRGULA>
    n.f7.accept(this);
    return nRes;
  }

  public R visit(final Params n) {
    R nRes = null;
    // f0 -> ParamLista()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ParamLista n) {
    R nRes = null;
    // f0 -> Param()
    n.f0.accept(this);
    // f1 -> ( PParam() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final PParam n) {
    R nRes = null;
    // f0 -> <VIRGULA>
    n.f0.accept(this);
    // f1 -> Param()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Param n) {
    R nRes = null;
    // f0 -> TipoEspecificador()
    n.f0.accept(this);
    // f1 -> <DOISPONTOS>
    n.f1.accept(this);
    // f2 -> <IDENTIFIER>
    n.f2.accept(this);
    // f3 -> ( ParamI() )?
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final ParamI n) {
    R nRes = null;
    // f0 -> <ACOLCHETE>
    n.f0.accept(this);
    // f1 -> ( %0 <DIGITO>
    // .. .. | %1 <IDENTIFIER> )?
    n.f1.accept(this);
    // f2 -> ( ParamIVetor() )*
    n.f2.accept(this);
    // f3 -> <FCOLCHETE>
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final ParamIVetor n) {
    R nRes = null;
    // f0 -> <VIRGULA>
    n.f0.accept(this);
    // f1 -> ( %0 <DIGITO>
    // .. .. | %1 <IDENTIFIER> )
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final CompostoDecl n) {
    R nRes = null;
    // f0 -> ( LocalDeclaracoes() )*
    n.f0.accept(this);
    // f1 -> CorpoDeclLista()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final LocalDeclaracoes n) {
    R nRes = null;
    // f0 -> VarDeclaracao()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final CorpoDeclLista n) {
    R nRes = null;
    // f0 -> Corpo()
    n.f0.accept(this);
    // f1 -> ( CLista() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final CLista n) {
    R nRes = null;
    // f0 -> Corpo()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Corpo n) {
    R nRes = null;
    // f0 -> . %0 ExpressaoDecl()
    // .. .. | %1 SelecaoDecl()
    // .. .. | %2 EscolhaDecl()
    // .. .. | %3 IteracaoDecl()
    // .. .. | %4 RetornoDecl()
    // .. .. | %5 EntradaSaidaDecl()
    // .. .. | %6 GDecl()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ExpressaoDecl n) {
    R nRes = null;
    // f0 -> . %0 #0 Expressao() #1 <PONTOEVIRGULA>
    // .. .. | %1 <PONTOEVIRGULA>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final SelecaoDecl n) {
    R nRes = null;
    // f0 -> <SE>
    n.f0.accept(this);
    // f1 -> <APARENTESE>
    n.f1.accept(this);
    // f2 -> CondicaoDecl()
    n.f2.accept(this);
    // f3 -> <FPARENTESE>
    n.f3.accept(this);
    // f4 -> <ENTAO>
    n.f4.accept(this);
    // f5 -> SelecaoDeclI()
    n.f5.accept(this);
    return nRes;
  }

  public R visit(final SelecaoDeclI n) {
    R nRes = null;
    // f0 -> . %0 #0 <INICIO_LITERAL>
    // .. .. . .. #1 ( Corpo() )+
    // .. .. . .. #2 <FIM_LITERAL> #3 <PONTOEVIRGULA> #4 SelecaoDeclII()
    // .. .. | %1 #0 ( Corpo() )+
    // .. .. . .. #1 SelecaoDeclII()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final SelecaoDeclII n) {
    R nRes = null;
    // f0 -> . %0 #0 <FIMSE> #1 <PONTOEVIRGULA>
    // .. .. | %1 #0 <SENAO> #1 SelecaoDeclIII()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final SelecaoDeclIII n) {
    R nRes = null;
    // f0 -> . %0 #0 <INICIO_LITERAL>
    // .. .. . .. #1 ( Corpo() )+
    // .. .. . .. #2 <FIM_LITERAL> #3 <PONTOEVIRGULA> #4 <FIMSE> #5 <PONTOEVIRGULA>
    // .. .. | %1 #0 ( Corpo() )+
    // .. .. . .. #1 <FIMSE> #2 <PONTOEVIRGULA>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final IteracaoDecl n) {
    R nRes = null;
    // f0 -> . %0 #0 <ENQUANTO> #1 <APARENTESE> #2 CondicaoDecl() #3 <FPARENTESE> #4 <FACA>
    // .. .. . .. #5 ( Corpo() )+
    // .. .. . .. #6 <FIMENQUANTO> #7 <PONTOEVIRGULA>
    // .. .. | %1 #0 <REPITA>
    // .. .. . .. #1 ( Corpo() )+
    // .. .. . .. #2 <ATE> #3 <APARENTESE> #4 CondicaoDecl() #5 <FPARENTESE> #6 <PONTOEVIRGULA>
    // .. .. | %2 #0 <PARA> #1 <IDENTIFIER> #2 <DE> #3 <DIGITO> #4 <ATE> #5 <DIGITO> #6 IteracaoDeclI()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final IteracaoDeclI n) {
    R nRes = null;
    // f0 -> . %0 #0 <FACA>
    // .. .. . .. #1 ( Corpo() )+
    // .. .. . .. #2 <FIMPARA> #3 <PONTOEVIRGULA>
    // .. .. | %1 #0 <PASSO>
    // .. .. . .. #1 ( <MENOS> )?
    // .. .. . .. #2 <DIGITO> #3 <FACA>
    // .. .. . .. #4 ( Corpo() )+
    // .. .. . .. #5 <FIMPARA> #6 <PONTOEVIRGULA>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final RetornoDecl n) {
    R nRes = null;
    // f0 -> <RETORNE>
    n.f0.accept(this);
    // f1 -> RetornoDeclI()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final RetornoDeclI n) {
    R nRes = null;
    // f0 -> . %0 <PONTOEVIRGULA>
    // .. .. | %1 #0 Expressao() #1 <PONTOEVIRGULA>
    // .. .. | %2 <FALSO>
    // .. .. | %3 <VERDADEIRO>
    // .. .. | %4 <STRING>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final EntradaSaidaDecl n) {
    R nRes = null;
    // f0 -> . %0 #0 <LEIA> #1 <APARENTESE> #2 Lendo() #3 <FPARENTESE> #4 <PONTOEVIRGULA>
    // .. .. | %1 #0 <ESCREVA> #1 <APARENTESE> #2 Escrevendo() #3 <FPARENTESE> #4 <PONTOEVIRGULA>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Lendo n) {
    R nRes = null;
    // f0 -> VarLerNum()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final VarLerNum n) {
    R nRes = null;
    // f0 -> VarItemLerNum()
    n.f0.accept(this);
    // f1 -> ( VLerNum() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final VLerNum n) {
    R nRes = null;
    // f0 -> <VIRGULA>
    n.f0.accept(this);
    // f1 -> VarLerNum()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final VarItemLerNum n) {
    R nRes = null;
    // f0 -> <IDENTIFIER>
    n.f0.accept(this);
    // f1 -> VarLerVetor()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final VarLerVetor n) {
    R nRes = null;
    // f0 -> ( %0 #0 <ACOLCHETE>
    // .. .. . .. #1 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #2 ( ParamIVetor() )*
    // .. .. . .. #3 <FCOLCHETE>
    // .. .. . .. #4 ( $0 <PONTO> $1 <IDENTIFIER>
    // .. .. . .. .. . $2 ( ?0 <ACOLCHETE>
    // .. .. . .. .. . .. . ?1 ( &0 <DIGITO>
    // .. .. . .. .. . .. . .. | &1 <IDENTIFIER> )
    // .. .. . .. .. . .. . ?2 ( ParamIVetor() )*
    // .. .. . .. .. . .. . ?3 <FCOLCHETE> )? )?
    // .. .. | %1 #0 <PONTO> #1 <IDENTIFIER>
    // .. .. . .. #2 ( $0 <ACOLCHETE>
    // .. .. . .. .. . $1 ( &0 <DIGITO>
    // .. .. . .. .. . .. | &1 <IDENTIFIER> )
    // .. .. . .. .. . $2 ( ParamIVetor() )*
    // .. .. . .. .. . $3 <FCOLCHETE> )? )?
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Escrevendo n) {
    R nRes = null;
    // f0 -> EscreveItem()
    n.f0.accept(this);
    // f1 -> ( EscrevendoRec() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final EscrevendoRec n) {
    R nRes = null;
    // f0 -> <VIRGULA>
    n.f0.accept(this);
    // f1 -> EscreveItem()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final EscreveItem n) {
    R nRes = null;
    // f0 -> . %0 #0 <IDENTIFIER> #1 VarLerVetor()
    // .. .. | %1 <STRING>
    // .. .. | %2 <FALSO>
    // .. .. | %3 <VERDADEIRO>
    // .. .. | %4 <DIGITO>
    // .. .. | %5 <PONTO_FLUTUANTE>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final EscolhaDecl n) {
    R nRes = null;
    // f0 -> <Escolha>
    n.f0.accept(this);
    // f1 -> <IDENTIFIER>
    n.f1.accept(this);
    // f2 -> EscolhaCaso()
    n.f2.accept(this);
    // f3 -> ( EscolhaExcessao() )?
    n.f3.accept(this);
    // f4 -> <FimEscolha>
    n.f4.accept(this);
    // f5 -> <PONTOEVIRGULA>
    n.f5.accept(this);
    return nRes;
  }

  public R visit(final EscolhaCaso n) {
    R nRes = null;
    // f0 -> EscCaso()
    n.f0.accept(this);
    // f1 -> ( EscolhaRec() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final EscolhaRec n) {
    R nRes = null;
    // f0 -> EscCaso()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final EscCaso n) {
    R nRes = null;
    // f0 -> <Caso>
    n.f0.accept(this);
    // f1 -> <DIGITO>
    n.f1.accept(this);
    // f2 -> <DOISPONTOS>
    n.f2.accept(this);
    // f3 -> ( Corpo() )+
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final EscolhaExcessao n) {
    R nRes = null;
    // f0 -> <Caso>
    n.f0.accept(this);
    // f1 -> <Contrario>
    n.f1.accept(this);
    // f2 -> <DOISPONTOS>
    n.f2.accept(this);
    // f3 -> ( Corpo() )+
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final Expressao n) {
    R nRes = null;
    // f0 -> SimplesEpressao()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final CondicaoDecl n) {
    R nRes = null;
    // f0 -> ExpressaoRelacional()
    n.f0.accept(this);
    // f1 -> Relacional()
    n.f1.accept(this);
    // f2 -> ExpressaoRelacional()
    n.f2.accept(this);
    // f3 -> ( #0 Logico() #1 ExpressaoRelacional() #2 Relacional() #3 ExpressaoRelacional() )*
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final Valor n) {
    R nRes = null;
    // f0 -> . %0 #0 ( <MENOS> )?
    // .. .. . .. #1 <DIGITO>
    // .. .. | %1 #0 ( <MENOS> )?
    // .. .. . .. #1 <IDENTIFIER>
    // .. .. . .. #2 [ Var() ]
    // .. .. | %2 #0 ( <MENOS> )?
    // .. .. . .. #1 <PONTO_FLUTUANTE>
    // .. .. | %3 <STRING>
    // .. .. | %4 <VERDADEIRO>
    // .. .. | %5 <FALSO>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ExpressaoRelacional n) {
    R nRes = null;
    // f0 -> . %0 Valor()
    // .. .. | %1 #0 <APARENTESE> #1 Valor() #2 <FPARENTESE>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final SimplesEpressao n) {
    R nRes = null;
    // f0 -> SomaExpressao()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Relacional n) {
    R nRes = null;
    // f0 -> . %0 <MENORIGUAL>
    // .. .. | %1 <MENOR>
    // .. .. | %2 <MAIOR>
    // .. .. | %3 <MAIORIGUAL>
    // .. .. | %4 <IGUAL>
    // .. .. | %5 <DIFERENTE>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Logico n) {
    R nRes = null;
    // f0 -> . %0 <E>
    // .. .. | %1 <OU>
    // .. .. | %2 <NAO>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final SomaExpressao n) {
    R nRes = null;
    // f0 -> Termo()
    n.f0.accept(this);
    // f1 -> ( SomaExpressaoI() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final SomaExpressaoI n) {
    R nRes = null;
    // f0 -> Soma()
    n.f0.accept(this);
    // f1 -> Termo()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Soma n) {
    R nRes = null;
    // f0 -> . %0 <MAIS>
    // .. .. | %1 <MENOS>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Termo n) {
    R nRes = null;
    // f0 -> Fator()
    n.f0.accept(this);
    // f1 -> ( TermoI() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final TermoI n) {
    R nRes = null;
    // f0 -> Mult()
    n.f0.accept(this);
    // f1 -> Fator()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Mult n) {
    R nRes = null;
    // f0 -> . %0 <MULTIPLICAR>
    // .. .. | %1 <DIVIDIR>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Fator n) {
    R nRes = null;
    // f0 -> . %0 #0 <APARENTESE> #1 SimplesEpressao() #2 <FPARENTESE>
    // .. .. | %1 #0 <IDENTIFIER> #1 VarAtivacao()
    // .. .. | %2 <DIGITO>
    // .. .. | %3 <PONTO_FLUTUANTE>
    // .. .. | %4 #0 <DIV> #1 <APARENTESE>
    // .. .. . .. #2 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #3 <VIRGULA>
    // .. .. . .. #4 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #5 <FPARENTESE>
    // .. .. | %5 #0 <MOD> #1 <APARENTESE>
    // .. .. . .. #2 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #3 <VIRGULA>
    // .. .. . .. #4 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #5 <FPARENTESE>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final VarAtivacao n) {
    R nRes = null;
    // f0 -> . %0 Ativacao()
    // .. .. | %1 #0 ( Var() )?
    // .. .. . .. #1 ( $0 <RECEBE>
    // .. .. . .. .. . $1 ( &0 SimplesEpressao()
    // .. .. . .. .. . .. | &1 ?0 ( <MENOS> )?
    // .. .. . .. .. . .. . .. ?1 <IDENTIFIER>
    // .. .. . .. .. . .. . .. ?2 ( Var() )?
    // .. .. . .. .. . .. | &2 ?0 ( <MENOS> )?
    // .. .. . .. .. . .. . .. ?1 <DIGITO>
    // .. .. . .. .. . .. | &3 ?0 ( <MENOS> )?
    // .. .. . .. .. . .. . .. ?1 <PONTO_FLUTUANTE>
    // .. .. . .. .. . .. | &4 <FALSO>
    // .. .. . .. .. . .. | &5 <VERDADEIRO>
    // .. .. . .. .. . .. | &6 <STRING> ) )?
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Var n) {
    R nRes = null;
    // f0 -> . %0 #0 <ACOLCHETE>
    // .. .. . .. #1 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #2 ( ParamIVetor() )*
    // .. .. . .. #3 <FCOLCHETE>
    // .. .. . .. #4 ( $0 <PONTO> $1 <IDENTIFIER>
    // .. .. . .. .. . $2 ( ?0 <ACOLCHETE>
    // .. .. . .. .. . .. . ?1 ( &0 <DIGITO>
    // .. .. . .. .. . .. . .. | &1 <IDENTIFIER> )
    // .. .. . .. .. . .. . ?2 ( ParamIVetor() )*
    // .. .. . .. .. . .. . ?3 <FCOLCHETE> )? )?
    // .. .. | %1 #0 <PONTO> #1 <IDENTIFIER>
    // .. .. . .. #2 ( $0 <ACOLCHETE>
    // .. .. . .. .. . $1 ( &0 <DIGITO>
    // .. .. . .. .. . .. | &1 <IDENTIFIER> )
    // .. .. . .. .. . $2 ( ParamIVetor() )*
    // .. .. . .. .. . $3 <FCOLCHETE> )?
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Ativacao n) {
    R nRes = null;
    // f0 -> <APARENTESE>
    n.f0.accept(this);
    // f1 -> ( Args() )?
    n.f1.accept(this);
    // f2 -> <FPARENTESE>
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final Args n) {
    R nRes = null;
    // f0 -> ArgLista()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ArgLista n) {
    R nRes = null;
    // f0 -> ( %0 <FALSO>
    // .. .. | %1 <VERDADEIRO>
    // .. .. | %2 #0 ( <MENOS> )?
    // .. .. . .. #1 <DIGITO>
    // .. .. | %3 #0 ( <MENOS> )?
    // .. .. . .. #1 <IDENTIFIER>
    // .. .. . .. #2 ( Var() )?
    // .. .. | %4 #0 ( <MENOS> )?
    // .. .. . .. #1 <PONTO_FLUTUANTE>
    // .. .. | %5 <STRING> )
    n.f0.accept(this);
    // f1 -> ( ArgListaRec() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ArgListaRec n) {
    R nRes = null;
    // f0 -> <VIRGULA>
    n.f0.accept(this);
    // f1 -> ( %0 <FALSO>
    // .. .. | %1 <VERDADEIRO>
    // .. .. | %2 #0 ( <MENOS> )?
    // .. .. . .. #1 <DIGITO>
    // .. .. | %3 #0 ( <MENOS> )?
    // .. .. . .. #1 <IDENTIFIER>
    // .. .. . .. #2 ( Var() )?
    // .. .. | %4 #0 ( <MENOS> )?
    // .. .. . .. #1 <PONTO_FLUTUANTE>
    // .. .. | %5 <STRING> )
    n.f1.accept(this);
    return nRes;
  }

}
