/* Generated by JTB 1.4.7 */
package Telas.visitor;

import Telas.syntaxtree.*;
import java.util.*;

public class DepthFirstVoidArguVisitor<A> implements IVoidArguVisitor<A> {


  public void visit(final NodeChoice n, final A argu) {
    n.choice.accept(this, argu);
    return;
  }

  public void visit(final NodeList n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  public void visit(final NodeListOptional n, final A argu) {
    if (n.present()) {
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        e.next().accept(this, argu);
        }
      return;
    } else
      return;
  }

  public void visit(final NodeOptional n, final A argu) {
    if (n.present()) {
      n.node.accept(this, argu);
      return;
    } else
      return;
  }

  public void visit(final NodeSequence n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  public void visit(final NodeTCF n, final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  public void visit(final NodeToken n, final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  public void visit(final Start n, final A argu) {
    // f0 -> Programa()
    n.f0.accept(this, argu);
  }

  public void visit(final Programa n, final A argu) {
    // f0 -> ( #0 <VAR>
    // .. .. . #1 ( %0 GDecl()
    // .. .. . .. | %1 FunDeclaracao() )+ )?
    n.f0.accept(this, argu);
    // f1 -> <INICIO_LITERAL>
    n.f1.accept(this, argu);
    // f2 -> Declaracao()
    n.f2.accept(this, argu);
    // f3 -> <FIMALGORITMO>
    n.f3.accept(this, argu);
    // f4 -> <EOF>
    n.f4.accept(this, argu);
  }

  public void visit(final Declaracao n, final A argu) {
    // f0 -> GlobalDeclaracao()
    n.f0.accept(this, argu);
    // f1 -> ( CorpoDeclLista() )*
    n.f1.accept(this, argu);
  }

  public void visit(final GlobalDeclaracao n, final A argu) {
    // f0 -> ( GDecl() )*
    n.f0.accept(this, argu);
    // f1 -> ( CorpoDeclLista() )*
    n.f1.accept(this, argu);
  }

  public void visit(final GDecl n, final A argu) {
    // f0 -> . %0 #0 <Tipo> #1 <IDENTIFIER> #2 <IGUAL> #3 DefTipo()
    // .. .. | %1 VarDeclaracao()
    n.f0.accept(this, argu);
  }

  public void visit(final DefTipo n, final A argu) {
    // f0 -> . %0 #0 <Registro>
    // .. .. . .. #1 ( VarDeclaracao() )+
    // .. .. . .. #2 <FimRegistro> #3 <PONTOEVIRGULA>
    // .. .. | %1 #0 <VETOR> #1 <ACOLCHETE> #2 <DIGITO> #3 <PONTOS> #4 <DIGITO> #5 <FCOLCHETE> #6 <DE>
    // .. .. . .. #7 ( &0 <TIPO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #8 <PONTOEVIRGULA>
    // .. .. | %2 #0 <MATRIZ> #1 <ACOLCHETE> #2 <DIGITO> #3 <PONTOS> #4 <DIGITO>
    // .. .. . .. #5 ( $0 <VIRGULA> $1 <DIGITO> $2 <PONTOS> $3 <DIGITO> )+
    // .. .. . .. #6 <FCOLCHETE> #7 <DE>
    // .. .. . .. #8 ( &0 <TIPO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #9 <PONTOEVIRGULA>
    n.f0.accept(this, argu);
  }

  public void visit(final TipoEspecificador n, final A argu) {
    // f0 -> . %0 <TIPO>
    // .. .. | %1 <IDENTIFIER>
    n.f0.accept(this, argu);
  }

  public void visit(final VarDeclaracao n, final A argu) {
    // f0 -> TipoEspecificador()
    n.f0.accept(this, argu);
    // f1 -> <DOISPONTOS>
    n.f1.accept(this, argu);
    // f2 -> VarDeclaracaoI()
    n.f2.accept(this, argu);
  }

  public void visit(final VarDeclaracaoI n, final A argu) {
    // f0 -> VarListaNum()
    n.f0.accept(this, argu);
    // f1 -> <PONTOEVIRGULA>
    n.f1.accept(this, argu);
  }

  public void visit(final VarListaNum n, final A argu) {
    // f0 -> VarItemNum()
    n.f0.accept(this, argu);
    // f1 -> ( VNum() )*
    n.f1.accept(this, argu);
  }

  public void visit(final VNum n, final A argu) {
    // f0 -> <VIRGULA>
    n.f0.accept(this, argu);
    // f1 -> VarItemNum()
    n.f1.accept(this, argu);
  }

  public void visit(final VarItemNum n, final A argu) {
    // f0 -> <IDENTIFIER>
    n.f0.accept(this, argu);
    // f1 -> VarItemVetor()
    n.f1.accept(this, argu);
  }

  public void visit(final VarItemVetor n, final A argu) {
    // f0 -> ( #0 <RECEBE> #1 VarComplemento() )?
    n.f0.accept(this, argu);
  }

  public void visit(final VarComplemento n, final A argu) {
    // f0 -> . %0 #0 ( <MENOS> )?
    // .. .. . .. #1 <DIGITO>
    // .. .. | %1 #0 ( <MENOS> )?
    // .. .. . .. #1 <IDENTIFIER>
    // .. .. | %2 #0 ( <MENOS> )?
    // .. .. . .. #1 <PONTO_FLUTUANTE>
    // .. .. | %3 <STRING>
    // .. .. | %4 <FALSO>
    // .. .. | %5 <VERDADEIRO>
    n.f0.accept(this, argu);
  }

  public void visit(final FunDeclaracao n, final A argu) {
    // f0 -> <MODULO>
    n.f0.accept(this, argu);
    // f1 -> <IDENTIFIER>
    n.f1.accept(this, argu);
    // f2 -> <APARENTESE>
    n.f2.accept(this, argu);
    // f3 -> ( Params() )?
    n.f3.accept(this, argu);
    // f4 -> <FPARENTESE>
    n.f4.accept(this, argu);
    // f5 -> CompostoDecl()
    n.f5.accept(this, argu);
    // f6 -> <FIMMODULO>
    n.f6.accept(this, argu);
    // f7 -> <PONTOEVIRGULA>
    n.f7.accept(this, argu);
  }

  public void visit(final Params n, final A argu) {
    // f0 -> ParamLista()
    n.f0.accept(this, argu);
  }

  public void visit(final ParamLista n, final A argu) {
    // f0 -> Param()
    n.f0.accept(this, argu);
    // f1 -> ( PParam() )*
    n.f1.accept(this, argu);
  }

  public void visit(final PParam n, final A argu) {
    // f0 -> <VIRGULA>
    n.f0.accept(this, argu);
    // f1 -> Param()
    n.f1.accept(this, argu);
  }

  public void visit(final Param n, final A argu) {
    // f0 -> TipoEspecificador()
    n.f0.accept(this, argu);
    // f1 -> <DOISPONTOS>
    n.f1.accept(this, argu);
    // f2 -> <IDENTIFIER>
    n.f2.accept(this, argu);
    // f3 -> ( ParamI() )?
    n.f3.accept(this, argu);
  }

  public void visit(final ParamI n, final A argu) {
    // f0 -> <ACOLCHETE>
    n.f0.accept(this, argu);
    // f1 -> ( %0 <DIGITO>
    // .. .. | %1 <IDENTIFIER> )?
    n.f1.accept(this, argu);
    // f2 -> ( ParamIVetor() )*
    n.f2.accept(this, argu);
    // f3 -> <FCOLCHETE>
    n.f3.accept(this, argu);
  }

  public void visit(final ParamIVetor n, final A argu) {
    // f0 -> <VIRGULA>
    n.f0.accept(this, argu);
    // f1 -> ( %0 <DIGITO>
    // .. .. | %1 <IDENTIFIER> )
    n.f1.accept(this, argu);
  }

  public void visit(final CompostoDecl n, final A argu) {
    // f0 -> ( LocalDeclaracoes() )*
    n.f0.accept(this, argu);
    // f1 -> CorpoDeclLista()
    n.f1.accept(this, argu);
  }

  public void visit(final LocalDeclaracoes n, final A argu) {
    // f0 -> VarDeclaracao()
    n.f0.accept(this, argu);
  }

  public void visit(final CorpoDeclLista n, final A argu) {
    // f0 -> Corpo()
    n.f0.accept(this, argu);
    // f1 -> ( CLista() )*
    n.f1.accept(this, argu);
  }

  public void visit(final CLista n, final A argu) {
    // f0 -> Corpo()
    n.f0.accept(this, argu);
  }

  public void visit(final Corpo n, final A argu) {
    // f0 -> . %0 ExpressaoDecl()
    // .. .. | %1 SelecaoDecl()
    // .. .. | %2 EscolhaDecl()
    // .. .. | %3 IteracaoDecl()
    // .. .. | %4 RetornoDecl()
    // .. .. | %5 EntradaSaidaDecl()
    // .. .. | %6 GDecl()
    n.f0.accept(this, argu);
  }

  public void visit(final ExpressaoDecl n, final A argu) {
    // f0 -> . %0 #0 Expressao() #1 <PONTOEVIRGULA>
    // .. .. | %1 <PONTOEVIRGULA>
    n.f0.accept(this, argu);
  }

  public void visit(final SelecaoDecl n, final A argu) {
    // f0 -> <SE>
    n.f0.accept(this, argu);
    // f1 -> <APARENTESE>
    n.f1.accept(this, argu);
    // f2 -> CondicaoDecl()
    n.f2.accept(this, argu);
    // f3 -> <FPARENTESE>
    n.f3.accept(this, argu);
    // f4 -> <ENTAO>
    n.f4.accept(this, argu);
    // f5 -> SelecaoDeclI()
    n.f5.accept(this, argu);
  }

  public void visit(final SelecaoDeclI n, final A argu) {
    // f0 -> . %0 #0 <INICIO_LITERAL>
    // .. .. . .. #1 ( Corpo() )+
    // .. .. . .. #2 <FIM_LITERAL> #3 <PONTOEVIRGULA> #4 SelecaoDeclII()
    // .. .. | %1 #0 ( Corpo() )+
    // .. .. . .. #1 SelecaoDeclII()
    n.f0.accept(this, argu);
  }

  public void visit(final SelecaoDeclII n, final A argu) {
    // f0 -> . %0 #0 <FIMSE> #1 <PONTOEVIRGULA>
    // .. .. | %1 #0 <SENAO> #1 SelecaoDeclIII()
    n.f0.accept(this, argu);
  }

  public void visit(final SelecaoDeclIII n, final A argu) {
    // f0 -> . %0 #0 <INICIO_LITERAL>
    // .. .. . .. #1 ( Corpo() )+
    // .. .. . .. #2 <FIM_LITERAL> #3 <PONTOEVIRGULA> #4 <FIMSE> #5 <PONTOEVIRGULA>
    // .. .. | %1 #0 ( Corpo() )+
    // .. .. . .. #1 <FIMSE> #2 <PONTOEVIRGULA>
    n.f0.accept(this, argu);
  }

  public void visit(final IteracaoDecl n, final A argu) {
    // f0 -> . %0 #0 <ENQUANTO> #1 <APARENTESE> #2 CondicaoDecl() #3 <FPARENTESE> #4 <FACA>
    // .. .. . .. #5 ( Corpo() )+
    // .. .. . .. #6 <FIMENQUANTO> #7 <PONTOEVIRGULA>
    // .. .. | %1 #0 <REPITA>
    // .. .. . .. #1 ( Corpo() )+
    // .. .. . .. #2 <ATE> #3 <APARENTESE> #4 CondicaoDecl() #5 <FPARENTESE> #6 <PONTOEVIRGULA>
    // .. .. | %2 #0 <PARA> #1 <IDENTIFIER> #2 <DE> #3 <DIGITO> #4 <ATE> #5 <DIGITO> #6 IteracaoDeclI()
    n.f0.accept(this, argu);
  }

  public void visit(final IteracaoDeclI n, final A argu) {
    // f0 -> . %0 #0 <FACA>
    // .. .. . .. #1 ( Corpo() )+
    // .. .. . .. #2 <FIMPARA> #3 <PONTOEVIRGULA>
    // .. .. | %1 #0 <PASSO>
    // .. .. . .. #1 ( <MENOS> )?
    // .. .. . .. #2 <DIGITO> #3 <FACA>
    // .. .. . .. #4 ( Corpo() )+
    // .. .. . .. #5 <FIMPARA> #6 <PONTOEVIRGULA>
    n.f0.accept(this, argu);
  }

  public void visit(final RetornoDecl n, final A argu) {
    // f0 -> <RETORNE>
    n.f0.accept(this, argu);
    // f1 -> RetornoDeclI()
    n.f1.accept(this, argu);
  }

  public void visit(final RetornoDeclI n, final A argu) {
    // f0 -> . %0 <PONTOEVIRGULA>
    // .. .. | %1 #0 Expressao() #1 <PONTOEVIRGULA>
    // .. .. | %2 <FALSO>
    // .. .. | %3 <VERDADEIRO>
    // .. .. | %4 <STRING>
    n.f0.accept(this, argu);
  }

  public void visit(final EntradaSaidaDecl n, final A argu) {
    // f0 -> . %0 #0 <LEIA> #1 <APARENTESE> #2 Lendo() #3 <FPARENTESE> #4 <PONTOEVIRGULA>
    // .. .. | %1 #0 <ESCREVA> #1 <APARENTESE> #2 Escrevendo() #3 <FPARENTESE> #4 <PONTOEVIRGULA>
    n.f0.accept(this, argu);
  }

  public void visit(final Lendo n, final A argu) {
    // f0 -> VarLerNum()
    n.f0.accept(this, argu);
  }

  public void visit(final VarLerNum n, final A argu) {
    // f0 -> VarItemLerNum()
    n.f0.accept(this, argu);
    // f1 -> ( VLerNum() )*
    n.f1.accept(this, argu);
  }

  public void visit(final VLerNum n, final A argu) {
    // f0 -> <VIRGULA>
    n.f0.accept(this, argu);
    // f1 -> VarLerNum()
    n.f1.accept(this, argu);
  }

  public void visit(final VarItemLerNum n, final A argu) {
    // f0 -> <IDENTIFIER>
    n.f0.accept(this, argu);
    // f1 -> VarLerVetor()
    n.f1.accept(this, argu);
  }

  public void visit(final VarLerVetor n, final A argu) {
    // f0 -> ( %0 #0 <ACOLCHETE>
    // .. .. . .. #1 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #2 ( ParamIVetor() )*
    // .. .. . .. #3 <FCOLCHETE>
    // .. .. . .. #4 ( $0 <PONTO> $1 <IDENTIFIER>
    // .. .. . .. .. . $2 ( ?0 <ACOLCHETE>
    // .. .. . .. .. . .. . ?1 ( &0 <DIGITO>
    // .. .. . .. .. . .. . .. | &1 <IDENTIFIER> )
    // .. .. . .. .. . .. . ?2 ( ParamIVetor() )*
    // .. .. . .. .. . .. . ?3 <FCOLCHETE> )? )?
    // .. .. | %1 #0 <PONTO> #1 <IDENTIFIER>
    // .. .. . .. #2 ( $0 <ACOLCHETE>
    // .. .. . .. .. . $1 ( &0 <DIGITO>
    // .. .. . .. .. . .. | &1 <IDENTIFIER> )
    // .. .. . .. .. . $2 ( ParamIVetor() )*
    // .. .. . .. .. . $3 <FCOLCHETE> )? )?
    n.f0.accept(this, argu);
  }

  public void visit(final Escrevendo n, final A argu) {
    // f0 -> EscreveItem()
    n.f0.accept(this, argu);
    // f1 -> ( EscrevendoRec() )*
    n.f1.accept(this, argu);
  }

  public void visit(final EscrevendoRec n, final A argu) {
    // f0 -> <VIRGULA>
    n.f0.accept(this, argu);
    // f1 -> EscreveItem()
    n.f1.accept(this, argu);
  }

  public void visit(final EscreveItem n, final A argu) {
    // f0 -> . %0 #0 <IDENTIFIER> #1 VarLerVetor()
    // .. .. | %1 <STRING>
    // .. .. | %2 <FALSO>
    // .. .. | %3 <VERDADEIRO>
    // .. .. | %4 <DIGITO>
    // .. .. | %5 <PONTO_FLUTUANTE>
    n.f0.accept(this, argu);
  }

  public void visit(final EscolhaDecl n, final A argu) {
    // f0 -> <Escolha>
    n.f0.accept(this, argu);
    // f1 -> <IDENTIFIER>
    n.f1.accept(this, argu);
    // f2 -> EscolhaCaso()
    n.f2.accept(this, argu);
    // f3 -> ( EscolhaExcessao() )?
    n.f3.accept(this, argu);
    // f4 -> <FimEscolha>
    n.f4.accept(this, argu);
    // f5 -> <PONTOEVIRGULA>
    n.f5.accept(this, argu);
  }

  public void visit(final EscolhaCaso n, final A argu) {
    // f0 -> EscCaso()
    n.f0.accept(this, argu);
    // f1 -> ( EscolhaRec() )*
    n.f1.accept(this, argu);
  }

  public void visit(final EscolhaRec n, final A argu) {
    // f0 -> EscCaso()
    n.f0.accept(this, argu);
  }

  public void visit(final EscCaso n, final A argu) {
    // f0 -> <Caso>
    n.f0.accept(this, argu);
    // f1 -> <DIGITO>
    n.f1.accept(this, argu);
    // f2 -> <DOISPONTOS>
    n.f2.accept(this, argu);
    // f3 -> ( Corpo() )+
    n.f3.accept(this, argu);
  }

  public void visit(final EscolhaExcessao n, final A argu) {
    // f0 -> <Caso>
    n.f0.accept(this, argu);
    // f1 -> <Contrario>
    n.f1.accept(this, argu);
    // f2 -> <DOISPONTOS>
    n.f2.accept(this, argu);
    // f3 -> ( Corpo() )+
    n.f3.accept(this, argu);
  }

  public void visit(final Expressao n, final A argu) {
    // f0 -> SimplesEpressao()
    n.f0.accept(this, argu);
  }

  public void visit(final CondicaoDecl n, final A argu) {
    // f0 -> ExpressaoRelacional()
    n.f0.accept(this, argu);
    // f1 -> Relacional()
    n.f1.accept(this, argu);
    // f2 -> ExpressaoRelacional()
    n.f2.accept(this, argu);
    // f3 -> ( #0 Logico() #1 ExpressaoRelacional() #2 Relacional() #3 ExpressaoRelacional() )*
    n.f3.accept(this, argu);
  }

  public void visit(final Valor n, final A argu) {
    // f0 -> . %0 #0 ( <MENOS> )?
    // .. .. . .. #1 <DIGITO>
    // .. .. | %1 #0 ( <MENOS> )?
    // .. .. . .. #1 <IDENTIFIER>
    // .. .. . .. #2 [ Var() ]
    // .. .. | %2 #0 ( <MENOS> )?
    // .. .. . .. #1 <PONTO_FLUTUANTE>
    // .. .. | %3 <STRING>
    // .. .. | %4 <VERDADEIRO>
    // .. .. | %5 <FALSO>
    n.f0.accept(this, argu);
  }

  public void visit(final ExpressaoRelacional n, final A argu) {
    // f0 -> . %0 Valor()
    // .. .. | %1 #0 <APARENTESE> #1 Valor() #2 <FPARENTESE>
    n.f0.accept(this, argu);
  }

  public void visit(final SimplesEpressao n, final A argu) {
    // f0 -> SomaExpressao()
    n.f0.accept(this, argu);
  }

  public void visit(final Relacional n, final A argu) {
    // f0 -> . %0 <MENORIGUAL>
    // .. .. | %1 <MENOR>
    // .. .. | %2 <MAIOR>
    // .. .. | %3 <MAIORIGUAL>
    // .. .. | %4 <IGUAL>
    // .. .. | %5 <DIFERENTE>
    n.f0.accept(this, argu);
  }

  public void visit(final Logico n, final A argu) {
    // f0 -> . %0 <E>
    // .. .. | %1 <OU>
    // .. .. | %2 <NAO>
    n.f0.accept(this, argu);
  }

  public void visit(final SomaExpressao n, final A argu) {
    // f0 -> Termo()
    n.f0.accept(this, argu);
    // f1 -> ( SomaExpressaoI() )*
    n.f1.accept(this, argu);
  }

  public void visit(final SomaExpressaoI n, final A argu) {
    // f0 -> Soma()
    n.f0.accept(this, argu);
    // f1 -> Termo()
    n.f1.accept(this, argu);
  }

  public void visit(final Soma n, final A argu) {
    // f0 -> . %0 <MAIS>
    // .. .. | %1 <MENOS>
    n.f0.accept(this, argu);
  }

  public void visit(final Termo n, final A argu) {
    // f0 -> Fator()
    n.f0.accept(this, argu);
    // f1 -> ( TermoI() )*
    n.f1.accept(this, argu);
  }

  public void visit(final TermoI n, final A argu) {
    // f0 -> Mult()
    n.f0.accept(this, argu);
    // f1 -> Fator()
    n.f1.accept(this, argu);
  }

  public void visit(final Mult n, final A argu) {
    // f0 -> . %0 <MULTIPLICAR>
    // .. .. | %1 <DIVIDIR>
    n.f0.accept(this, argu);
  }

  public void visit(final Fator n, final A argu) {
    // f0 -> . %0 #0 <APARENTESE> #1 SimplesEpressao() #2 <FPARENTESE>
    // .. .. | %1 #0 <IDENTIFIER> #1 VarAtivacao()
    // .. .. | %2 <DIGITO>
    // .. .. | %3 <PONTO_FLUTUANTE>
    // .. .. | %4 #0 <DIV> #1 <APARENTESE>
    // .. .. . .. #2 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #3 <VIRGULA>
    // .. .. . .. #4 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #5 <FPARENTESE>
    // .. .. | %5 #0 <MOD> #1 <APARENTESE>
    // .. .. . .. #2 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #3 <VIRGULA>
    // .. .. . .. #4 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #5 <FPARENTESE>
    n.f0.accept(this, argu);
  }

  public void visit(final VarAtivacao n, final A argu) {
    // f0 -> . %0 Ativacao()
    // .. .. | %1 #0 ( Var() )?
    // .. .. . .. #1 ( $0 <RECEBE>
    // .. .. . .. .. . $1 ( &0 SimplesEpressao()
    // .. .. . .. .. . .. | &1 ?0 ( <MENOS> )?
    // .. .. . .. .. . .. . .. ?1 <IDENTIFIER>
    // .. .. . .. .. . .. . .. ?2 ( Var() )?
    // .. .. . .. .. . .. | &2 ?0 ( <MENOS> )?
    // .. .. . .. .. . .. . .. ?1 <DIGITO>
    // .. .. . .. .. . .. | &3 ?0 ( <MENOS> )?
    // .. .. . .. .. . .. . .. ?1 <PONTO_FLUTUANTE>
    // .. .. . .. .. . .. | &4 <FALSO>
    // .. .. . .. .. . .. | &5 <VERDADEIRO>
    // .. .. . .. .. . .. | &6 <STRING> ) )?
    n.f0.accept(this, argu);
  }

  public void visit(final Var n, final A argu) {
    // f0 -> . %0 #0 <ACOLCHETE>
    // .. .. . .. #1 ( &0 <DIGITO>
    // .. .. . .. .. | &1 <IDENTIFIER> )
    // .. .. . .. #2 ( ParamIVetor() )*
    // .. .. . .. #3 <FCOLCHETE>
    // .. .. . .. #4 ( $0 <PONTO> $1 <IDENTIFIER>
    // .. .. . .. .. . $2 ( ?0 <ACOLCHETE>
    // .. .. . .. .. . .. . ?1 ( &0 <DIGITO>
    // .. .. . .. .. . .. . .. | &1 <IDENTIFIER> )
    // .. .. . .. .. . .. . ?2 ( ParamIVetor() )*
    // .. .. . .. .. . .. . ?3 <FCOLCHETE> )? )?
    // .. .. | %1 #0 <PONTO> #1 <IDENTIFIER>
    // .. .. . .. #2 ( $0 <ACOLCHETE>
    // .. .. . .. .. . $1 ( &0 <DIGITO>
    // .. .. . .. .. . .. | &1 <IDENTIFIER> )
    // .. .. . .. .. . $2 ( ParamIVetor() )*
    // .. .. . .. .. . $3 <FCOLCHETE> )?
    n.f0.accept(this, argu);
  }

  public void visit(final Ativacao n, final A argu) {
    // f0 -> <APARENTESE>
    n.f0.accept(this, argu);
    // f1 -> ( Args() )?
    n.f1.accept(this, argu);
    // f2 -> <FPARENTESE>
    n.f2.accept(this, argu);
  }

  public void visit(final Args n, final A argu) {
    // f0 -> ArgLista()
    n.f0.accept(this, argu);
  }

  public void visit(final ArgLista n, final A argu) {
    // f0 -> ( %0 <FALSO>
    // .. .. | %1 <VERDADEIRO>
    // .. .. | %2 #0 ( <MENOS> )?
    // .. .. . .. #1 <DIGITO>
    // .. .. | %3 #0 ( <MENOS> )?
    // .. .. . .. #1 <IDENTIFIER>
    // .. .. . .. #2 ( Var() )?
    // .. .. | %4 #0 ( <MENOS> )?
    // .. .. . .. #1 <PONTO_FLUTUANTE>
    // .. .. | %5 <STRING> )
    n.f0.accept(this, argu);
    // f1 -> ( ArgListaRec() )*
    n.f1.accept(this, argu);
  }

  public void visit(final ArgListaRec n, final A argu) {
    // f0 -> <VIRGULA>
    n.f0.accept(this, argu);
    // f1 -> ( %0 <FALSO>
    // .. .. | %1 <VERDADEIRO>
    // .. .. | %2 #0 ( <MENOS> )?
    // .. .. . .. #1 <DIGITO>
    // .. .. | %3 #0 ( <MENOS> )?
    // .. .. . .. #1 <IDENTIFIER>
    // .. .. . .. #2 ( Var() )?
    // .. .. | %4 #0 ( <MENOS> )?
    // .. .. . .. #1 <PONTO_FLUTUANTE>
    // .. .. | %5 <STRING> )
    n.f1.accept(this, argu);
  }

}
