/* Generated by JTB 1.4.7 */
package Telas.visitor;

import Telas.syntaxtree.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeChoice n, final A argu);

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeTCF n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final Start n, final A argu);

  public R visit(final Programa n, final A argu);

  public R visit(final Declaracao n, final A argu);

  public R visit(final GlobalDeclaracao n, final A argu);

  public R visit(final GDecl n, final A argu);

  public R visit(final DefTipo n, final A argu);

  public R visit(final TipoEspecificador n, final A argu);

  public R visit(final VarDeclaracao n, final A argu);

  public R visit(final VarDeclaracaoI n, final A argu);

  public R visit(final VarListaNum n, final A argu);

  public R visit(final VNum n, final A argu);

  public R visit(final VarItemNum n, final A argu);

  public R visit(final VarItemVetor n, final A argu);

  public R visit(final VarComplemento n, final A argu);

  public R visit(final FunDeclaracao n, final A argu);

  public R visit(final Params n, final A argu);

  public R visit(final ParamLista n, final A argu);

  public R visit(final PParam n, final A argu);

  public R visit(final Param n, final A argu);

  public R visit(final ParamI n, final A argu);

  public R visit(final ParamIVetor n, final A argu);

  public R visit(final CompostoDecl n, final A argu);

  public R visit(final LocalDeclaracoes n, final A argu);

  public R visit(final CorpoDeclLista n, final A argu);

  public R visit(final CLista n, final A argu);

  public R visit(final Corpo n, final A argu);

  public R visit(final ExpressaoDecl n, final A argu);

  public R visit(final SelecaoDecl n, final A argu);

  public R visit(final SelecaoDeclI n, final A argu);

  public R visit(final SelecaoDeclII n, final A argu);

  public R visit(final SelecaoDeclIII n, final A argu);

  public R visit(final IteracaoDecl n, final A argu);

  public R visit(final IteracaoDeclI n, final A argu);

  public R visit(final RetornoDecl n, final A argu);

  public R visit(final RetornoDeclI n, final A argu);

  public R visit(final EntradaSaidaDecl n, final A argu);

  public R visit(final Lendo n, final A argu);

  public R visit(final VarLerNum n, final A argu);

  public R visit(final VLerNum n, final A argu);

  public R visit(final VarItemLerNum n, final A argu);

  public R visit(final VarLerVetor n, final A argu);

  public R visit(final Escrevendo n, final A argu);

  public R visit(final EscrevendoRec n, final A argu);

  public R visit(final EscreveItem n, final A argu);

  public R visit(final EscolhaDecl n, final A argu);

  public R visit(final EscolhaCaso n, final A argu);

  public R visit(final EscolhaRec n, final A argu);

  public R visit(final EscCaso n, final A argu);

  public R visit(final EscolhaExcessao n, final A argu);

  public R visit(final Expressao n, final A argu);

  public R visit(final CondicaoDecl n, final A argu);

  public R visit(final Valor n, final A argu);

  public R visit(final ExpressaoRelacional n, final A argu);

  public R visit(final SimplesEpressao n, final A argu);

  public R visit(final Relacional n, final A argu);

  public R visit(final Logico n, final A argu);

  public R visit(final SomaExpressao n, final A argu);

  public R visit(final SomaExpressaoI n, final A argu);

  public R visit(final Soma n, final A argu);

  public R visit(final Termo n, final A argu);

  public R visit(final TermoI n, final A argu);

  public R visit(final Mult n, final A argu);

  public R visit(final Fator n, final A argu);

  public R visit(final VarAtivacao n, final A argu);

  public R visit(final Var n, final A argu);

  public R visit(final Ativacao n, final A argu);

  public R visit(final Args n, final A argu);

  public R visit(final ArgLista n, final A argu);

  public R visit(final ArgListaRec n, final A argu);

}
