/* Generated by JTB 1.4.7 */
package Telas.visitor;

import Telas.syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeChoice n);

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeTCF n);

  public R visit(final NodeToken n);

  public R visit(final Start n);

  public R visit(final Programa n);

  public R visit(final Declaracao n);

  public R visit(final GlobalDeclaracao n);

  public R visit(final GDecl n);

  public R visit(final DefTipo n);

  public R visit(final TipoEspecificador n);

  public R visit(final VarDeclaracao n);

  public R visit(final VarDeclaracaoI n);

  public R visit(final VarListaNum n);

  public R visit(final VNum n);

  public R visit(final VarItemNum n);

  public R visit(final VarItemVetor n);

  public R visit(final VarComplemento n);

  public R visit(final FunDeclaracao n);

  public R visit(final Params n);

  public R visit(final ParamLista n);

  public R visit(final PParam n);

  public R visit(final Param n);

  public R visit(final ParamI n);

  public R visit(final ParamIVetor n);

  public R visit(final CompostoDecl n);

  public R visit(final LocalDeclaracoes n);

  public R visit(final CorpoDeclLista n);

  public R visit(final CLista n);

  public R visit(final Corpo n);

  public R visit(final ExpressaoDecl n);

  public R visit(final SelecaoDecl n);

  public R visit(final SelecaoDeclI n);

  public R visit(final SelecaoDeclII n);

  public R visit(final SelecaoDeclIII n);

  public R visit(final IteracaoDecl n);

  public R visit(final IteracaoDeclI n);

  public R visit(final RetornoDecl n);

  public R visit(final RetornoDeclI n);

  public R visit(final EntradaSaidaDecl n);

  public R visit(final Lendo n);

  public R visit(final VarLerNum n);

  public R visit(final VLerNum n);

  public R visit(final VarItemLerNum n);

  public R visit(final VarLerVetor n);

  public R visit(final Escrevendo n);

  public R visit(final EscrevendoRec n);

  public R visit(final EscreveItem n);

  public R visit(final EscolhaDecl n);

  public R visit(final EscolhaCaso n);

  public R visit(final EscolhaRec n);

  public R visit(final EscCaso n);

  public R visit(final EscolhaExcessao n);

  public R visit(final Expressao n);

  public R visit(final CondicaoDecl n);

  public R visit(final Valor n);

  public R visit(final ExpressaoRelacional n);

  public R visit(final SimplesEpressao n);

  public R visit(final Relacional n);

  public R visit(final Logico n);

  public R visit(final SomaExpressao n);

  public R visit(final SomaExpressaoI n);

  public R visit(final Soma n);

  public R visit(final Termo n);

  public R visit(final TermoI n);

  public R visit(final Mult n);

  public R visit(final Fator n);

  public R visit(final VarAtivacao n);

  public R visit(final Var n);

  public R visit(final Ativacao n);

  public R visit(final Args n);

  public R visit(final ArgLista n);

  public R visit(final ArgListaRec n);

}
