/* Generated by JTB 1.4.7 */
package Telas.visitor;

import Telas.syntaxtree.*;

public interface IVoidArguVisitor<A> {

  public void visit(final NodeChoice n, final A argu);

  public void visit(final NodeList n, final A argu);

  public void visit(final NodeListOptional n, final A argu);

  public void visit(final NodeOptional n, final A argu);

  public void visit(final NodeSequence n, final A argu);

  public void visit(final NodeTCF n, final A argu);

  public void visit(final NodeToken n, final A argu);

  public void visit(final Start n, final A argu);

  public void visit(final Programa n, final A argu);

  public void visit(final Declaracao n, final A argu);

  public void visit(final GlobalDeclaracao n, final A argu);

  public void visit(final GDecl n, final A argu);

  public void visit(final DefTipo n, final A argu);

  public void visit(final TipoEspecificador n, final A argu);

  public void visit(final VarDeclaracao n, final A argu);

  public void visit(final VarDeclaracaoI n, final A argu);

  public void visit(final VarListaNum n, final A argu);

  public void visit(final VNum n, final A argu);

  public void visit(final VarItemNum n, final A argu);

  public void visit(final VarItemVetor n, final A argu);

  public void visit(final VarComplemento n, final A argu);

  public void visit(final FunDeclaracao n, final A argu);

  public void visit(final Params n, final A argu);

  public void visit(final ParamLista n, final A argu);

  public void visit(final PParam n, final A argu);

  public void visit(final Param n, final A argu);

  public void visit(final ParamI n, final A argu);

  public void visit(final ParamIVetor n, final A argu);

  public void visit(final CompostoDecl n, final A argu);

  public void visit(final LocalDeclaracoes n, final A argu);

  public void visit(final CorpoDeclLista n, final A argu);

  public void visit(final CLista n, final A argu);

  public void visit(final Corpo n, final A argu);

  public void visit(final ExpressaoDecl n, final A argu);

  public void visit(final SelecaoDecl n, final A argu);

  public void visit(final SelecaoDeclI n, final A argu);

  public void visit(final SelecaoDeclII n, final A argu);

  public void visit(final SelecaoDeclIII n, final A argu);

  public void visit(final IteracaoDecl n, final A argu);

  public void visit(final IteracaoDeclI n, final A argu);

  public void visit(final RetornoDecl n, final A argu);

  public void visit(final RetornoDeclI n, final A argu);

  public void visit(final EntradaSaidaDecl n, final A argu);

  public void visit(final Lendo n, final A argu);

  public void visit(final VarLerNum n, final A argu);

  public void visit(final VLerNum n, final A argu);

  public void visit(final VarItemLerNum n, final A argu);

  public void visit(final VarLerVetor n, final A argu);

  public void visit(final Escrevendo n, final A argu);

  public void visit(final EscrevendoRec n, final A argu);

  public void visit(final EscreveItem n, final A argu);

  public void visit(final EscolhaDecl n, final A argu);

  public void visit(final EscolhaCaso n, final A argu);

  public void visit(final EscolhaRec n, final A argu);

  public void visit(final EscCaso n, final A argu);

  public void visit(final EscolhaExcessao n, final A argu);

  public void visit(final Expressao n, final A argu);

  public void visit(final CondicaoDecl n, final A argu);

  public void visit(final Valor n, final A argu);

  public void visit(final ExpressaoRelacional n, final A argu);

  public void visit(final SimplesEpressao n, final A argu);

  public void visit(final Relacional n, final A argu);

  public void visit(final Logico n, final A argu);

  public void visit(final SomaExpressao n, final A argu);

  public void visit(final SomaExpressaoI n, final A argu);

  public void visit(final Soma n, final A argu);

  public void visit(final Termo n, final A argu);

  public void visit(final TermoI n, final A argu);

  public void visit(final Mult n, final A argu);

  public void visit(final Fator n, final A argu);

  public void visit(final VarAtivacao n, final A argu);

  public void visit(final Var n, final A argu);

  public void visit(final Ativacao n, final A argu);

  public void visit(final Args n, final A argu);

  public void visit(final ArgLista n, final A argu);

  public void visit(final ArgListaRec n, final A argu);

}
