/* Generated by JTB 1.4.7 */
package Telas.syntaxtree;

import Telas.visitor.*;

public class CondicaoDecl implements INode {

  public ExpressaoRelacional f0;

  public Relacional f1;

  public ExpressaoRelacional f2;

  public NodeListOptional f3;

  private static final long serialVersionUID = 147L;

  public CondicaoDecl(final ExpressaoRelacional n0, final Relacional n1, final ExpressaoRelacional n2, final NodeListOptional n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
